
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductInclude` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProductInclude
 * 
 */
export type ProductIncludeModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductIncludePayload>

export type AggregateProductInclude = {
  _count: ProductIncludeCountAggregateOutputType | null
  _avg: ProductIncludeAvgAggregateOutputType | null
  _sum: ProductIncludeSumAggregateOutputType | null
  _min: ProductIncludeMinAggregateOutputType | null
  _max: ProductIncludeMaxAggregateOutputType | null
}

export type ProductIncludeAvgAggregateOutputType = {
  quantity: number | null
}

export type ProductIncludeSumAggregateOutputType = {
  quantity: number | null
}

export type ProductIncludeMinAggregateOutputType = {
  id: string | null
  product_id: string | null
  quantity: number | null
  item: string | null
}

export type ProductIncludeMaxAggregateOutputType = {
  id: string | null
  product_id: string | null
  quantity: number | null
  item: string | null
}

export type ProductIncludeCountAggregateOutputType = {
  id: number
  product_id: number
  quantity: number
  item: number
  _all: number
}


export type ProductIncludeAvgAggregateInputType = {
  quantity?: true
}

export type ProductIncludeSumAggregateInputType = {
  quantity?: true
}

export type ProductIncludeMinAggregateInputType = {
  id?: true
  product_id?: true
  quantity?: true
  item?: true
}

export type ProductIncludeMaxAggregateInputType = {
  id?: true
  product_id?: true
  quantity?: true
  item?: true
}

export type ProductIncludeCountAggregateInputType = {
  id?: true
  product_id?: true
  quantity?: true
  item?: true
  _all?: true
}

export type ProductIncludeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductInclude to aggregate.
   */
  where?: Prisma.ProductIncludeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductIncludes to fetch.
   */
  orderBy?: Prisma.ProductIncludeOrderByWithRelationInput | Prisma.ProductIncludeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductIncludeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductIncludes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductIncludes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductIncludes
  **/
  _count?: true | ProductIncludeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProductIncludeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProductIncludeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductIncludeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductIncludeMaxAggregateInputType
}

export type GetProductIncludeAggregateType<T extends ProductIncludeAggregateArgs> = {
      [P in keyof T & keyof AggregateProductInclude]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductInclude[P]>
    : Prisma.GetScalarType<T[P], AggregateProductInclude[P]>
}




export type ProductIncludeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductIncludeWhereInput
  orderBy?: Prisma.ProductIncludeOrderByWithAggregationInput | Prisma.ProductIncludeOrderByWithAggregationInput[]
  by: Prisma.ProductIncludeScalarFieldEnum[] | Prisma.ProductIncludeScalarFieldEnum
  having?: Prisma.ProductIncludeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductIncludeCountAggregateInputType | true
  _avg?: ProductIncludeAvgAggregateInputType
  _sum?: ProductIncludeSumAggregateInputType
  _min?: ProductIncludeMinAggregateInputType
  _max?: ProductIncludeMaxAggregateInputType
}

export type ProductIncludeGroupByOutputType = {
  id: string
  product_id: string
  quantity: number
  item: string
  _count: ProductIncludeCountAggregateOutputType | null
  _avg: ProductIncludeAvgAggregateOutputType | null
  _sum: ProductIncludeSumAggregateOutputType | null
  _min: ProductIncludeMinAggregateOutputType | null
  _max: ProductIncludeMaxAggregateOutputType | null
}

type GetProductIncludeGroupByPayload<T extends ProductIncludeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductIncludeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductIncludeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductIncludeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductIncludeGroupByOutputType[P]>
      }
    >
  >



export type ProductIncludeWhereInput = {
  AND?: Prisma.ProductIncludeWhereInput | Prisma.ProductIncludeWhereInput[]
  OR?: Prisma.ProductIncludeWhereInput[]
  NOT?: Prisma.ProductIncludeWhereInput | Prisma.ProductIncludeWhereInput[]
  id?: Prisma.StringFilter<"ProductInclude"> | string
  product_id?: Prisma.StringFilter<"ProductInclude"> | string
  quantity?: Prisma.IntFilter<"ProductInclude"> | number
  item?: Prisma.StringFilter<"ProductInclude"> | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type ProductIncludeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  product_id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  item?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type ProductIncludeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProductIncludeWhereInput | Prisma.ProductIncludeWhereInput[]
  OR?: Prisma.ProductIncludeWhereInput[]
  NOT?: Prisma.ProductIncludeWhereInput | Prisma.ProductIncludeWhereInput[]
  product_id?: Prisma.StringFilter<"ProductInclude"> | string
  quantity?: Prisma.IntFilter<"ProductInclude"> | number
  item?: Prisma.StringFilter<"ProductInclude"> | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id">

export type ProductIncludeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  product_id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  item?: Prisma.SortOrder
  _count?: Prisma.ProductIncludeCountOrderByAggregateInput
  _avg?: Prisma.ProductIncludeAvgOrderByAggregateInput
  _max?: Prisma.ProductIncludeMaxOrderByAggregateInput
  _min?: Prisma.ProductIncludeMinOrderByAggregateInput
  _sum?: Prisma.ProductIncludeSumOrderByAggregateInput
}

export type ProductIncludeScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductIncludeScalarWhereWithAggregatesInput | Prisma.ProductIncludeScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductIncludeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductIncludeScalarWhereWithAggregatesInput | Prisma.ProductIncludeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProductInclude"> | string
  product_id?: Prisma.StringWithAggregatesFilter<"ProductInclude"> | string
  quantity?: Prisma.IntWithAggregatesFilter<"ProductInclude"> | number
  item?: Prisma.StringWithAggregatesFilter<"ProductInclude"> | string
}

export type ProductIncludeCreateInput = {
  id?: string
  quantity: number
  item: string
  product: Prisma.ProductCreateNestedOneWithoutIncludesInput
}

export type ProductIncludeUncheckedCreateInput = {
  id?: string
  product_id: string
  quantity: number
  item: string
}

export type ProductIncludeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  item?: Prisma.StringFieldUpdateOperationsInput | string
  product?: Prisma.ProductUpdateOneRequiredWithoutIncludesNestedInput
}

export type ProductIncludeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  product_id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductIncludeCreateManyInput = {
  id?: string
  product_id: string
  quantity: number
  item: string
}

export type ProductIncludeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductIncludeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  product_id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductIncludeListRelationFilter = {
  every?: Prisma.ProductIncludeWhereInput
  some?: Prisma.ProductIncludeWhereInput
  none?: Prisma.ProductIncludeWhereInput
}

export type ProductIncludeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductIncludeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  product_id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  item?: Prisma.SortOrder
}

export type ProductIncludeAvgOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type ProductIncludeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  product_id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  item?: Prisma.SortOrder
}

export type ProductIncludeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  product_id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  item?: Prisma.SortOrder
}

export type ProductIncludeSumOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type ProductIncludeCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductIncludeCreateWithoutProductInput, Prisma.ProductIncludeUncheckedCreateWithoutProductInput> | Prisma.ProductIncludeCreateWithoutProductInput[] | Prisma.ProductIncludeUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductIncludeCreateOrConnectWithoutProductInput | Prisma.ProductIncludeCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductIncludeCreateManyProductInputEnvelope
  connect?: Prisma.ProductIncludeWhereUniqueInput | Prisma.ProductIncludeWhereUniqueInput[]
}

export type ProductIncludeUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductIncludeCreateWithoutProductInput, Prisma.ProductIncludeUncheckedCreateWithoutProductInput> | Prisma.ProductIncludeCreateWithoutProductInput[] | Prisma.ProductIncludeUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductIncludeCreateOrConnectWithoutProductInput | Prisma.ProductIncludeCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductIncludeCreateManyProductInputEnvelope
  connect?: Prisma.ProductIncludeWhereUniqueInput | Prisma.ProductIncludeWhereUniqueInput[]
}

export type ProductIncludeUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductIncludeCreateWithoutProductInput, Prisma.ProductIncludeUncheckedCreateWithoutProductInput> | Prisma.ProductIncludeCreateWithoutProductInput[] | Prisma.ProductIncludeUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductIncludeCreateOrConnectWithoutProductInput | Prisma.ProductIncludeCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductIncludeUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductIncludeUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductIncludeCreateManyProductInputEnvelope
  set?: Prisma.ProductIncludeWhereUniqueInput | Prisma.ProductIncludeWhereUniqueInput[]
  disconnect?: Prisma.ProductIncludeWhereUniqueInput | Prisma.ProductIncludeWhereUniqueInput[]
  delete?: Prisma.ProductIncludeWhereUniqueInput | Prisma.ProductIncludeWhereUniqueInput[]
  connect?: Prisma.ProductIncludeWhereUniqueInput | Prisma.ProductIncludeWhereUniqueInput[]
  update?: Prisma.ProductIncludeUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductIncludeUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductIncludeUpdateManyWithWhereWithoutProductInput | Prisma.ProductIncludeUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductIncludeScalarWhereInput | Prisma.ProductIncludeScalarWhereInput[]
}

export type ProductIncludeUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductIncludeCreateWithoutProductInput, Prisma.ProductIncludeUncheckedCreateWithoutProductInput> | Prisma.ProductIncludeCreateWithoutProductInput[] | Prisma.ProductIncludeUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductIncludeCreateOrConnectWithoutProductInput | Prisma.ProductIncludeCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductIncludeUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductIncludeUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductIncludeCreateManyProductInputEnvelope
  set?: Prisma.ProductIncludeWhereUniqueInput | Prisma.ProductIncludeWhereUniqueInput[]
  disconnect?: Prisma.ProductIncludeWhereUniqueInput | Prisma.ProductIncludeWhereUniqueInput[]
  delete?: Prisma.ProductIncludeWhereUniqueInput | Prisma.ProductIncludeWhereUniqueInput[]
  connect?: Prisma.ProductIncludeWhereUniqueInput | Prisma.ProductIncludeWhereUniqueInput[]
  update?: Prisma.ProductIncludeUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductIncludeUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductIncludeUpdateManyWithWhereWithoutProductInput | Prisma.ProductIncludeUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductIncludeScalarWhereInput | Prisma.ProductIncludeScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ProductIncludeCreateWithoutProductInput = {
  id?: string
  quantity: number
  item: string
}

export type ProductIncludeUncheckedCreateWithoutProductInput = {
  id?: string
  quantity: number
  item: string
}

export type ProductIncludeCreateOrConnectWithoutProductInput = {
  where: Prisma.ProductIncludeWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductIncludeCreateWithoutProductInput, Prisma.ProductIncludeUncheckedCreateWithoutProductInput>
}

export type ProductIncludeCreateManyProductInputEnvelope = {
  data: Prisma.ProductIncludeCreateManyProductInput | Prisma.ProductIncludeCreateManyProductInput[]
}

export type ProductIncludeUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductIncludeWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductIncludeUpdateWithoutProductInput, Prisma.ProductIncludeUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ProductIncludeCreateWithoutProductInput, Prisma.ProductIncludeUncheckedCreateWithoutProductInput>
}

export type ProductIncludeUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductIncludeWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductIncludeUpdateWithoutProductInput, Prisma.ProductIncludeUncheckedUpdateWithoutProductInput>
}

export type ProductIncludeUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.ProductIncludeScalarWhereInput
  data: Prisma.XOR<Prisma.ProductIncludeUpdateManyMutationInput, Prisma.ProductIncludeUncheckedUpdateManyWithoutProductInput>
}

export type ProductIncludeScalarWhereInput = {
  AND?: Prisma.ProductIncludeScalarWhereInput | Prisma.ProductIncludeScalarWhereInput[]
  OR?: Prisma.ProductIncludeScalarWhereInput[]
  NOT?: Prisma.ProductIncludeScalarWhereInput | Prisma.ProductIncludeScalarWhereInput[]
  id?: Prisma.StringFilter<"ProductInclude"> | string
  product_id?: Prisma.StringFilter<"ProductInclude"> | string
  quantity?: Prisma.IntFilter<"ProductInclude"> | number
  item?: Prisma.StringFilter<"ProductInclude"> | string
}

export type ProductIncludeCreateManyProductInput = {
  id?: string
  quantity: number
  item: string
}

export type ProductIncludeUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductIncludeUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  item?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductIncludeUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  item?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ProductIncludeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  product_id?: boolean
  quantity?: boolean
  item?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productInclude"]>

export type ProductIncludeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  product_id?: boolean
  quantity?: boolean
  item?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productInclude"]>

export type ProductIncludeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  product_id?: boolean
  quantity?: boolean
  item?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productInclude"]>

export type ProductIncludeSelectScalar = {
  id?: boolean
  product_id?: boolean
  quantity?: boolean
  item?: boolean
}

export type ProductIncludeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "product_id" | "quantity" | "item", ExtArgs["result"]["productInclude"]>
export type ProductIncludeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductIncludeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductIncludeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $ProductIncludePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductInclude"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    product_id: string
    quantity: number
    item: string
  }, ExtArgs["result"]["productInclude"]>
  composites: {}
}

export type ProductIncludeGetPayload<S extends boolean | null | undefined | ProductIncludeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload, S>

export type ProductIncludeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductIncludeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductIncludeCountAggregateInputType | true
  }

export interface ProductIncludeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductInclude'], meta: { name: 'ProductInclude' } }
  /**
   * Find zero or one ProductInclude that matches the filter.
   * @param {ProductIncludeFindUniqueArgs} args - Arguments to find a ProductInclude
   * @example
   * // Get one ProductInclude
   * const productInclude = await prisma.productInclude.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductIncludeFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductIncludeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductIncludeClient<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductInclude that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductIncludeFindUniqueOrThrowArgs} args - Arguments to find a ProductInclude
   * @example
   * // Get one ProductInclude
   * const productInclude = await prisma.productInclude.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductIncludeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductIncludeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductIncludeClient<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductInclude that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductIncludeFindFirstArgs} args - Arguments to find a ProductInclude
   * @example
   * // Get one ProductInclude
   * const productInclude = await prisma.productInclude.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductIncludeFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductIncludeFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductIncludeClient<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductInclude that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductIncludeFindFirstOrThrowArgs} args - Arguments to find a ProductInclude
   * @example
   * // Get one ProductInclude
   * const productInclude = await prisma.productInclude.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductIncludeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductIncludeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductIncludeClient<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductIncludes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductIncludeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductIncludes
   * const productIncludes = await prisma.productInclude.findMany()
   * 
   * // Get first 10 ProductIncludes
   * const productIncludes = await prisma.productInclude.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productIncludeWithIdOnly = await prisma.productInclude.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductIncludeFindManyArgs>(args?: Prisma.SelectSubset<T, ProductIncludeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductInclude.
   * @param {ProductIncludeCreateArgs} args - Arguments to create a ProductInclude.
   * @example
   * // Create one ProductInclude
   * const ProductInclude = await prisma.productInclude.create({
   *   data: {
   *     // ... data to create a ProductInclude
   *   }
   * })
   * 
   */
  create<T extends ProductIncludeCreateArgs>(args: Prisma.SelectSubset<T, ProductIncludeCreateArgs<ExtArgs>>): Prisma.Prisma__ProductIncludeClient<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductIncludes.
   * @param {ProductIncludeCreateManyArgs} args - Arguments to create many ProductIncludes.
   * @example
   * // Create many ProductIncludes
   * const productInclude = await prisma.productInclude.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductIncludeCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductIncludeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductIncludes and returns the data saved in the database.
   * @param {ProductIncludeCreateManyAndReturnArgs} args - Arguments to create many ProductIncludes.
   * @example
   * // Create many ProductIncludes
   * const productInclude = await prisma.productInclude.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductIncludes and only return the `id`
   * const productIncludeWithIdOnly = await prisma.productInclude.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductIncludeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductIncludeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductInclude.
   * @param {ProductIncludeDeleteArgs} args - Arguments to delete one ProductInclude.
   * @example
   * // Delete one ProductInclude
   * const ProductInclude = await prisma.productInclude.delete({
   *   where: {
   *     // ... filter to delete one ProductInclude
   *   }
   * })
   * 
   */
  delete<T extends ProductIncludeDeleteArgs>(args: Prisma.SelectSubset<T, ProductIncludeDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductIncludeClient<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductInclude.
   * @param {ProductIncludeUpdateArgs} args - Arguments to update one ProductInclude.
   * @example
   * // Update one ProductInclude
   * const productInclude = await prisma.productInclude.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductIncludeUpdateArgs>(args: Prisma.SelectSubset<T, ProductIncludeUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductIncludeClient<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductIncludes.
   * @param {ProductIncludeDeleteManyArgs} args - Arguments to filter ProductIncludes to delete.
   * @example
   * // Delete a few ProductIncludes
   * const { count } = await prisma.productInclude.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductIncludeDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductIncludeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductIncludes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductIncludeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductIncludes
   * const productInclude = await prisma.productInclude.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductIncludeUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductIncludeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductIncludes and returns the data updated in the database.
   * @param {ProductIncludeUpdateManyAndReturnArgs} args - Arguments to update many ProductIncludes.
   * @example
   * // Update many ProductIncludes
   * const productInclude = await prisma.productInclude.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductIncludes and only return the `id`
   * const productIncludeWithIdOnly = await prisma.productInclude.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductIncludeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductIncludeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductInclude.
   * @param {ProductIncludeUpsertArgs} args - Arguments to update or create a ProductInclude.
   * @example
   * // Update or create a ProductInclude
   * const productInclude = await prisma.productInclude.upsert({
   *   create: {
   *     // ... data to create a ProductInclude
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductInclude we want to update
   *   }
   * })
   */
  upsert<T extends ProductIncludeUpsertArgs>(args: Prisma.SelectSubset<T, ProductIncludeUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductIncludeClient<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductIncludes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductIncludeCountArgs} args - Arguments to filter ProductIncludes to count.
   * @example
   * // Count the number of ProductIncludes
   * const count = await prisma.productInclude.count({
   *   where: {
   *     // ... the filter for the ProductIncludes we want to count
   *   }
   * })
  **/
  count<T extends ProductIncludeCountArgs>(
    args?: Prisma.Subset<T, ProductIncludeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductIncludeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductInclude.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductIncludeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductIncludeAggregateArgs>(args: Prisma.Subset<T, ProductIncludeAggregateArgs>): Prisma.PrismaPromise<GetProductIncludeAggregateType<T>>

  /**
   * Group by ProductInclude.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductIncludeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductIncludeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductIncludeGroupByArgs['orderBy'] }
      : { orderBy?: ProductIncludeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductIncludeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductIncludeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductInclude model
 */
readonly fields: ProductIncludeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductInclude.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductIncludeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductInclude model
 */
export interface ProductIncludeFieldRefs {
  readonly id: Prisma.FieldRef<"ProductInclude", 'String'>
  readonly product_id: Prisma.FieldRef<"ProductInclude", 'String'>
  readonly quantity: Prisma.FieldRef<"ProductInclude", 'Int'>
  readonly item: Prisma.FieldRef<"ProductInclude", 'String'>
}
    

// Custom InputTypes
/**
 * ProductInclude findUnique
 */
export type ProductIncludeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
  /**
   * Filter, which ProductInclude to fetch.
   */
  where: Prisma.ProductIncludeWhereUniqueInput
}

/**
 * ProductInclude findUniqueOrThrow
 */
export type ProductIncludeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
  /**
   * Filter, which ProductInclude to fetch.
   */
  where: Prisma.ProductIncludeWhereUniqueInput
}

/**
 * ProductInclude findFirst
 */
export type ProductIncludeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
  /**
   * Filter, which ProductInclude to fetch.
   */
  where?: Prisma.ProductIncludeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductIncludes to fetch.
   */
  orderBy?: Prisma.ProductIncludeOrderByWithRelationInput | Prisma.ProductIncludeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductIncludes.
   */
  cursor?: Prisma.ProductIncludeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductIncludes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductIncludes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductIncludes.
   */
  distinct?: Prisma.ProductIncludeScalarFieldEnum | Prisma.ProductIncludeScalarFieldEnum[]
}

/**
 * ProductInclude findFirstOrThrow
 */
export type ProductIncludeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
  /**
   * Filter, which ProductInclude to fetch.
   */
  where?: Prisma.ProductIncludeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductIncludes to fetch.
   */
  orderBy?: Prisma.ProductIncludeOrderByWithRelationInput | Prisma.ProductIncludeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductIncludes.
   */
  cursor?: Prisma.ProductIncludeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductIncludes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductIncludes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductIncludes.
   */
  distinct?: Prisma.ProductIncludeScalarFieldEnum | Prisma.ProductIncludeScalarFieldEnum[]
}

/**
 * ProductInclude findMany
 */
export type ProductIncludeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
  /**
   * Filter, which ProductIncludes to fetch.
   */
  where?: Prisma.ProductIncludeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductIncludes to fetch.
   */
  orderBy?: Prisma.ProductIncludeOrderByWithRelationInput | Prisma.ProductIncludeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductIncludes.
   */
  cursor?: Prisma.ProductIncludeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductIncludes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductIncludes.
   */
  skip?: number
  distinct?: Prisma.ProductIncludeScalarFieldEnum | Prisma.ProductIncludeScalarFieldEnum[]
}

/**
 * ProductInclude create
 */
export type ProductIncludeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductInclude.
   */
  data: Prisma.XOR<Prisma.ProductIncludeCreateInput, Prisma.ProductIncludeUncheckedCreateInput>
}

/**
 * ProductInclude createMany
 */
export type ProductIncludeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductIncludes.
   */
  data: Prisma.ProductIncludeCreateManyInput | Prisma.ProductIncludeCreateManyInput[]
}

/**
 * ProductInclude createManyAndReturn
 */
export type ProductIncludeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * The data used to create many ProductIncludes.
   */
  data: Prisma.ProductIncludeCreateManyInput | Prisma.ProductIncludeCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProductInclude update
 */
export type ProductIncludeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductInclude.
   */
  data: Prisma.XOR<Prisma.ProductIncludeUpdateInput, Prisma.ProductIncludeUncheckedUpdateInput>
  /**
   * Choose, which ProductInclude to update.
   */
  where: Prisma.ProductIncludeWhereUniqueInput
}

/**
 * ProductInclude updateMany
 */
export type ProductIncludeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductIncludes.
   */
  data: Prisma.XOR<Prisma.ProductIncludeUpdateManyMutationInput, Prisma.ProductIncludeUncheckedUpdateManyInput>
  /**
   * Filter which ProductIncludes to update
   */
  where?: Prisma.ProductIncludeWhereInput
  /**
   * Limit how many ProductIncludes to update.
   */
  limit?: number
}

/**
 * ProductInclude updateManyAndReturn
 */
export type ProductIncludeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * The data used to update ProductIncludes.
   */
  data: Prisma.XOR<Prisma.ProductIncludeUpdateManyMutationInput, Prisma.ProductIncludeUncheckedUpdateManyInput>
  /**
   * Filter which ProductIncludes to update
   */
  where?: Prisma.ProductIncludeWhereInput
  /**
   * Limit how many ProductIncludes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProductInclude upsert
 */
export type ProductIncludeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductInclude to update in case it exists.
   */
  where: Prisma.ProductIncludeWhereUniqueInput
  /**
   * In case the ProductInclude found by the `where` argument doesn't exist, create a new ProductInclude with this data.
   */
  create: Prisma.XOR<Prisma.ProductIncludeCreateInput, Prisma.ProductIncludeUncheckedCreateInput>
  /**
   * In case the ProductInclude was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductIncludeUpdateInput, Prisma.ProductIncludeUncheckedUpdateInput>
}

/**
 * ProductInclude delete
 */
export type ProductIncludeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
  /**
   * Filter which ProductInclude to delete.
   */
  where: Prisma.ProductIncludeWhereUniqueInput
}

/**
 * ProductInclude deleteMany
 */
export type ProductIncludeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductIncludes to delete
   */
  where?: Prisma.ProductIncludeWhereInput
  /**
   * Limit how many ProductIncludes to delete.
   */
  limit?: number
}

/**
 * ProductInclude without action
 */
export type ProductIncludeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
}
