
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Product` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Product
 * 
 */
export type ProductModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductPayload>

export type AggregateProduct = {
  _count: ProductCountAggregateOutputType | null
  _avg: ProductAvgAggregateOutputType | null
  _sum: ProductSumAggregateOutputType | null
  _min: ProductMinAggregateOutputType | null
  _max: ProductMaxAggregateOutputType | null
}

export type ProductAvgAggregateOutputType = {
  id: number | null
  category_id: number | null
  price: runtime.Decimal | null
}

export type ProductSumAggregateOutputType = {
  id: number | null
  category_id: number | null
  price: runtime.Decimal | null
}

export type ProductMinAggregateOutputType = {
  id: number | null
  slug: string | null
  name: string | null
  category_id: number | null
  new: boolean | null
  price: runtime.Decimal | null
  description: string | null
  features: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type ProductMaxAggregateOutputType = {
  id: number | null
  slug: string | null
  name: string | null
  category_id: number | null
  new: boolean | null
  price: runtime.Decimal | null
  description: string | null
  features: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type ProductCountAggregateOutputType = {
  id: number
  slug: number
  name: number
  category_id: number
  new: number
  price: number
  description: number
  features: number
  created_at: number
  updated_at: number
  _all: number
}


export type ProductAvgAggregateInputType = {
  id?: true
  category_id?: true
  price?: true
}

export type ProductSumAggregateInputType = {
  id?: true
  category_id?: true
  price?: true
}

export type ProductMinAggregateInputType = {
  id?: true
  slug?: true
  name?: true
  category_id?: true
  new?: true
  price?: true
  description?: true
  features?: true
  created_at?: true
  updated_at?: true
}

export type ProductMaxAggregateInputType = {
  id?: true
  slug?: true
  name?: true
  category_id?: true
  new?: true
  price?: true
  description?: true
  features?: true
  created_at?: true
  updated_at?: true
}

export type ProductCountAggregateInputType = {
  id?: true
  slug?: true
  name?: true
  category_id?: true
  new?: true
  price?: true
  description?: true
  features?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type ProductAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Product to aggregate.
   */
  where?: Prisma.ProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Products to fetch.
   */
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Products from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Products.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Products
  **/
  _count?: true | ProductCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProductAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProductSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductMaxAggregateInputType
}

export type GetProductAggregateType<T extends ProductAggregateArgs> = {
      [P in keyof T & keyof AggregateProduct]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProduct[P]>
    : Prisma.GetScalarType<T[P], AggregateProduct[P]>
}




export type ProductGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithAggregationInput | Prisma.ProductOrderByWithAggregationInput[]
  by: Prisma.ProductScalarFieldEnum[] | Prisma.ProductScalarFieldEnum
  having?: Prisma.ProductScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductCountAggregateInputType | true
  _avg?: ProductAvgAggregateInputType
  _sum?: ProductSumAggregateInputType
  _min?: ProductMinAggregateInputType
  _max?: ProductMaxAggregateInputType
}

export type ProductGroupByOutputType = {
  id: number
  slug: string
  name: string
  category_id: number
  new: boolean
  price: runtime.Decimal
  description: string
  features: string
  created_at: Date
  updated_at: Date
  _count: ProductCountAggregateOutputType | null
  _avg: ProductAvgAggregateOutputType | null
  _sum: ProductSumAggregateOutputType | null
  _min: ProductMinAggregateOutputType | null
  _max: ProductMaxAggregateOutputType | null
}

type GetProductGroupByPayload<T extends ProductGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductGroupByOutputType[P]>
      }
    >
  >



export type ProductWhereInput = {
  AND?: Prisma.ProductWhereInput | Prisma.ProductWhereInput[]
  OR?: Prisma.ProductWhereInput[]
  NOT?: Prisma.ProductWhereInput | Prisma.ProductWhereInput[]
  id?: Prisma.IntFilter<"Product"> | number
  slug?: Prisma.StringFilter<"Product"> | string
  name?: Prisma.StringFilter<"Product"> | string
  category_id?: Prisma.IntFilter<"Product"> | number
  new?: Prisma.BoolFilter<"Product"> | boolean
  price?: Prisma.DecimalFilter<"Product"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFilter<"Product"> | string
  features?: Prisma.StringFilter<"Product"> | string
  created_at?: Prisma.DateTimeFilter<"Product"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Product"> | Date | string
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
  images?: Prisma.ProductImageListRelationFilter
  includes?: Prisma.ProductIncludeListRelationFilter
  orders?: Prisma.OrderItemListRelationFilter
  related_to?: Prisma.RelatedProductListRelationFilter
  related_from?: Prisma.RelatedProductListRelationFilter
}

export type ProductOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  new?: Prisma.SortOrder
  price?: Prisma.SortOrder
  description?: Prisma.SortOrder
  features?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  category?: Prisma.CategoryOrderByWithRelationInput
  images?: Prisma.ProductImageOrderByRelationAggregateInput
  includes?: Prisma.ProductIncludeOrderByRelationAggregateInput
  orders?: Prisma.OrderItemOrderByRelationAggregateInput
  related_to?: Prisma.RelatedProductOrderByRelationAggregateInput
  related_from?: Prisma.RelatedProductOrderByRelationAggregateInput
}

export type ProductWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  slug?: string
  AND?: Prisma.ProductWhereInput | Prisma.ProductWhereInput[]
  OR?: Prisma.ProductWhereInput[]
  NOT?: Prisma.ProductWhereInput | Prisma.ProductWhereInput[]
  name?: Prisma.StringFilter<"Product"> | string
  category_id?: Prisma.IntFilter<"Product"> | number
  new?: Prisma.BoolFilter<"Product"> | boolean
  price?: Prisma.DecimalFilter<"Product"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFilter<"Product"> | string
  features?: Prisma.StringFilter<"Product"> | string
  created_at?: Prisma.DateTimeFilter<"Product"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Product"> | Date | string
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
  images?: Prisma.ProductImageListRelationFilter
  includes?: Prisma.ProductIncludeListRelationFilter
  orders?: Prisma.OrderItemListRelationFilter
  related_to?: Prisma.RelatedProductListRelationFilter
  related_from?: Prisma.RelatedProductListRelationFilter
}, "id" | "slug">

export type ProductOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  new?: Prisma.SortOrder
  price?: Prisma.SortOrder
  description?: Prisma.SortOrder
  features?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.ProductCountOrderByAggregateInput
  _avg?: Prisma.ProductAvgOrderByAggregateInput
  _max?: Prisma.ProductMaxOrderByAggregateInput
  _min?: Prisma.ProductMinOrderByAggregateInput
  _sum?: Prisma.ProductSumOrderByAggregateInput
}

export type ProductScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductScalarWhereWithAggregatesInput | Prisma.ProductScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductScalarWhereWithAggregatesInput | Prisma.ProductScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Product"> | number
  slug?: Prisma.StringWithAggregatesFilter<"Product"> | string
  name?: Prisma.StringWithAggregatesFilter<"Product"> | string
  category_id?: Prisma.IntWithAggregatesFilter<"Product"> | number
  new?: Prisma.BoolWithAggregatesFilter<"Product"> | boolean
  price?: Prisma.DecimalWithAggregatesFilter<"Product"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringWithAggregatesFilter<"Product"> | string
  features?: Prisma.StringWithAggregatesFilter<"Product"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Product"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Product"> | Date | string
}

export type ProductCreateInput = {
  slug: string
  name: string
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutProductsInput
  images?: Prisma.ProductImageCreateNestedManyWithoutProductInput
  includes?: Prisma.ProductIncludeCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductCreateNestedManyWithoutRelatedInput
}

export type ProductUncheckedCreateInput = {
  id?: number
  slug: string
  name: string
  category_id: number
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  images?: Prisma.ProductImageUncheckedCreateNestedManyWithoutProductInput
  includes?: Prisma.ProductIncludeUncheckedCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemUncheckedCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutRelatedInput
}

export type ProductUpdateInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutProductsNestedInput
  images?: Prisma.ProductImageUpdateManyWithoutProductNestedInput
  includes?: Prisma.ProductIncludeUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUpdateManyWithoutRelatedNestedInput
}

export type ProductUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.IntFieldUpdateOperationsInput | number
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProductImageUncheckedUpdateManyWithoutProductNestedInput
  includes?: Prisma.ProductIncludeUncheckedUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUncheckedUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUncheckedUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUncheckedUpdateManyWithoutRelatedNestedInput
}

export type ProductCreateManyInput = {
  id?: number
  slug: string
  name: string
  category_id: number
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ProductUpdateManyMutationInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.IntFieldUpdateOperationsInput | number
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductListRelationFilter = {
  every?: Prisma.ProductWhereInput
  some?: Prisma.ProductWhereInput
  none?: Prisma.ProductWhereInput
}

export type ProductOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  new?: Prisma.SortOrder
  price?: Prisma.SortOrder
  description?: Prisma.SortOrder
  features?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ProductAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type ProductMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  new?: Prisma.SortOrder
  price?: Prisma.SortOrder
  description?: Prisma.SortOrder
  features?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ProductMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  new?: Prisma.SortOrder
  price?: Prisma.SortOrder
  description?: Prisma.SortOrder
  features?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ProductSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type ProductScalarRelationFilter = {
  is?: Prisma.ProductWhereInput
  isNot?: Prisma.ProductWhereInput
}

export type ProductNullableScalarRelationFilter = {
  is?: Prisma.ProductWhereInput | null
  isNot?: Prisma.ProductWhereInput | null
}

export type ProductCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutCategoryInput, Prisma.ProductUncheckedCreateWithoutCategoryInput> | Prisma.ProductCreateWithoutCategoryInput[] | Prisma.ProductUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutCategoryInput | Prisma.ProductCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.ProductCreateManyCategoryInputEnvelope
  connect?: Prisma.ProductWhereUniqueInput | Prisma.ProductWhereUniqueInput[]
}

export type ProductUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutCategoryInput, Prisma.ProductUncheckedCreateWithoutCategoryInput> | Prisma.ProductCreateWithoutCategoryInput[] | Prisma.ProductUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutCategoryInput | Prisma.ProductCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.ProductCreateManyCategoryInputEnvelope
  connect?: Prisma.ProductWhereUniqueInput | Prisma.ProductWhereUniqueInput[]
}

export type ProductUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutCategoryInput, Prisma.ProductUncheckedCreateWithoutCategoryInput> | Prisma.ProductCreateWithoutCategoryInput[] | Prisma.ProductUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutCategoryInput | Prisma.ProductCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.ProductUpsertWithWhereUniqueWithoutCategoryInput | Prisma.ProductUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.ProductCreateManyCategoryInputEnvelope
  set?: Prisma.ProductWhereUniqueInput | Prisma.ProductWhereUniqueInput[]
  disconnect?: Prisma.ProductWhereUniqueInput | Prisma.ProductWhereUniqueInput[]
  delete?: Prisma.ProductWhereUniqueInput | Prisma.ProductWhereUniqueInput[]
  connect?: Prisma.ProductWhereUniqueInput | Prisma.ProductWhereUniqueInput[]
  update?: Prisma.ProductUpdateWithWhereUniqueWithoutCategoryInput | Prisma.ProductUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.ProductUpdateManyWithWhereWithoutCategoryInput | Prisma.ProductUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.ProductScalarWhereInput | Prisma.ProductScalarWhereInput[]
}

export type ProductUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutCategoryInput, Prisma.ProductUncheckedCreateWithoutCategoryInput> | Prisma.ProductCreateWithoutCategoryInput[] | Prisma.ProductUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutCategoryInput | Prisma.ProductCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.ProductUpsertWithWhereUniqueWithoutCategoryInput | Prisma.ProductUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.ProductCreateManyCategoryInputEnvelope
  set?: Prisma.ProductWhereUniqueInput | Prisma.ProductWhereUniqueInput[]
  disconnect?: Prisma.ProductWhereUniqueInput | Prisma.ProductWhereUniqueInput[]
  delete?: Prisma.ProductWhereUniqueInput | Prisma.ProductWhereUniqueInput[]
  connect?: Prisma.ProductWhereUniqueInput | Prisma.ProductWhereUniqueInput[]
  update?: Prisma.ProductUpdateWithWhereUniqueWithoutCategoryInput | Prisma.ProductUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.ProductUpdateManyWithWhereWithoutCategoryInput | Prisma.ProductUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.ProductScalarWhereInput | Prisma.ProductScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type ProductCreateNestedOneWithoutImagesInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutImagesInput, Prisma.ProductUncheckedCreateWithoutImagesInput>
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutImagesInput
  connect?: Prisma.ProductWhereUniqueInput
}

export type ProductUpdateOneRequiredWithoutImagesNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutImagesInput, Prisma.ProductUncheckedCreateWithoutImagesInput>
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutImagesInput
  upsert?: Prisma.ProductUpsertWithoutImagesInput
  connect?: Prisma.ProductWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProductUpdateToOneWithWhereWithoutImagesInput, Prisma.ProductUpdateWithoutImagesInput>, Prisma.ProductUncheckedUpdateWithoutImagesInput>
}

export type ProductCreateNestedOneWithoutIncludesInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutIncludesInput, Prisma.ProductUncheckedCreateWithoutIncludesInput>
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutIncludesInput
  connect?: Prisma.ProductWhereUniqueInput
}

export type ProductUpdateOneRequiredWithoutIncludesNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutIncludesInput, Prisma.ProductUncheckedCreateWithoutIncludesInput>
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutIncludesInput
  upsert?: Prisma.ProductUpsertWithoutIncludesInput
  connect?: Prisma.ProductWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProductUpdateToOneWithWhereWithoutIncludesInput, Prisma.ProductUpdateWithoutIncludesInput>, Prisma.ProductUncheckedUpdateWithoutIncludesInput>
}

export type ProductCreateNestedOneWithoutRelated_toInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutRelated_toInput, Prisma.ProductUncheckedCreateWithoutRelated_toInput>
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutRelated_toInput
  connect?: Prisma.ProductWhereUniqueInput
}

export type ProductCreateNestedOneWithoutRelated_fromInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutRelated_fromInput, Prisma.ProductUncheckedCreateWithoutRelated_fromInput>
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutRelated_fromInput
  connect?: Prisma.ProductWhereUniqueInput
}

export type ProductUpdateOneRequiredWithoutRelated_toNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutRelated_toInput, Prisma.ProductUncheckedCreateWithoutRelated_toInput>
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutRelated_toInput
  upsert?: Prisma.ProductUpsertWithoutRelated_toInput
  connect?: Prisma.ProductWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProductUpdateToOneWithWhereWithoutRelated_toInput, Prisma.ProductUpdateWithoutRelated_toInput>, Prisma.ProductUncheckedUpdateWithoutRelated_toInput>
}

export type ProductUpdateOneRequiredWithoutRelated_fromNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutRelated_fromInput, Prisma.ProductUncheckedCreateWithoutRelated_fromInput>
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutRelated_fromInput
  upsert?: Prisma.ProductUpsertWithoutRelated_fromInput
  connect?: Prisma.ProductWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProductUpdateToOneWithWhereWithoutRelated_fromInput, Prisma.ProductUpdateWithoutRelated_fromInput>, Prisma.ProductUncheckedUpdateWithoutRelated_fromInput>
}

export type ProductCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutOrdersInput, Prisma.ProductUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutOrdersInput
  connect?: Prisma.ProductWhereUniqueInput
}

export type ProductUpdateOneWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.ProductCreateWithoutOrdersInput, Prisma.ProductUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.ProductCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.ProductUpsertWithoutOrdersInput
  disconnect?: Prisma.ProductWhereInput | boolean
  delete?: Prisma.ProductWhereInput | boolean
  connect?: Prisma.ProductWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProductUpdateToOneWithWhereWithoutOrdersInput, Prisma.ProductUpdateWithoutOrdersInput>, Prisma.ProductUncheckedUpdateWithoutOrdersInput>
}

export type ProductCreateWithoutCategoryInput = {
  slug: string
  name: string
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  images?: Prisma.ProductImageCreateNestedManyWithoutProductInput
  includes?: Prisma.ProductIncludeCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductCreateNestedManyWithoutRelatedInput
}

export type ProductUncheckedCreateWithoutCategoryInput = {
  id?: number
  slug: string
  name: string
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  images?: Prisma.ProductImageUncheckedCreateNestedManyWithoutProductInput
  includes?: Prisma.ProductIncludeUncheckedCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemUncheckedCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutRelatedInput
}

export type ProductCreateOrConnectWithoutCategoryInput = {
  where: Prisma.ProductWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductCreateWithoutCategoryInput, Prisma.ProductUncheckedCreateWithoutCategoryInput>
}

export type ProductCreateManyCategoryInputEnvelope = {
  data: Prisma.ProductCreateManyCategoryInput | Prisma.ProductCreateManyCategoryInput[]
}

export type ProductUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.ProductWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductUpdateWithoutCategoryInput, Prisma.ProductUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.ProductCreateWithoutCategoryInput, Prisma.ProductUncheckedCreateWithoutCategoryInput>
}

export type ProductUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.ProductWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductUpdateWithoutCategoryInput, Prisma.ProductUncheckedUpdateWithoutCategoryInput>
}

export type ProductUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.ProductScalarWhereInput
  data: Prisma.XOR<Prisma.ProductUpdateManyMutationInput, Prisma.ProductUncheckedUpdateManyWithoutCategoryInput>
}

export type ProductScalarWhereInput = {
  AND?: Prisma.ProductScalarWhereInput | Prisma.ProductScalarWhereInput[]
  OR?: Prisma.ProductScalarWhereInput[]
  NOT?: Prisma.ProductScalarWhereInput | Prisma.ProductScalarWhereInput[]
  id?: Prisma.IntFilter<"Product"> | number
  slug?: Prisma.StringFilter<"Product"> | string
  name?: Prisma.StringFilter<"Product"> | string
  category_id?: Prisma.IntFilter<"Product"> | number
  new?: Prisma.BoolFilter<"Product"> | boolean
  price?: Prisma.DecimalFilter<"Product"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFilter<"Product"> | string
  features?: Prisma.StringFilter<"Product"> | string
  created_at?: Prisma.DateTimeFilter<"Product"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Product"> | Date | string
}

export type ProductCreateWithoutImagesInput = {
  slug: string
  name: string
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutProductsInput
  includes?: Prisma.ProductIncludeCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductCreateNestedManyWithoutRelatedInput
}

export type ProductUncheckedCreateWithoutImagesInput = {
  id?: number
  slug: string
  name: string
  category_id: number
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  includes?: Prisma.ProductIncludeUncheckedCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemUncheckedCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutRelatedInput
}

export type ProductCreateOrConnectWithoutImagesInput = {
  where: Prisma.ProductWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductCreateWithoutImagesInput, Prisma.ProductUncheckedCreateWithoutImagesInput>
}

export type ProductUpsertWithoutImagesInput = {
  update: Prisma.XOR<Prisma.ProductUpdateWithoutImagesInput, Prisma.ProductUncheckedUpdateWithoutImagesInput>
  create: Prisma.XOR<Prisma.ProductCreateWithoutImagesInput, Prisma.ProductUncheckedCreateWithoutImagesInput>
  where?: Prisma.ProductWhereInput
}

export type ProductUpdateToOneWithWhereWithoutImagesInput = {
  where?: Prisma.ProductWhereInput
  data: Prisma.XOR<Prisma.ProductUpdateWithoutImagesInput, Prisma.ProductUncheckedUpdateWithoutImagesInput>
}

export type ProductUpdateWithoutImagesInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutProductsNestedInput
  includes?: Prisma.ProductIncludeUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUpdateManyWithoutRelatedNestedInput
}

export type ProductUncheckedUpdateWithoutImagesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.IntFieldUpdateOperationsInput | number
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  includes?: Prisma.ProductIncludeUncheckedUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUncheckedUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUncheckedUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUncheckedUpdateManyWithoutRelatedNestedInput
}

export type ProductCreateWithoutIncludesInput = {
  slug: string
  name: string
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutProductsInput
  images?: Prisma.ProductImageCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductCreateNestedManyWithoutRelatedInput
}

export type ProductUncheckedCreateWithoutIncludesInput = {
  id?: number
  slug: string
  name: string
  category_id: number
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  images?: Prisma.ProductImageUncheckedCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemUncheckedCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutRelatedInput
}

export type ProductCreateOrConnectWithoutIncludesInput = {
  where: Prisma.ProductWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductCreateWithoutIncludesInput, Prisma.ProductUncheckedCreateWithoutIncludesInput>
}

export type ProductUpsertWithoutIncludesInput = {
  update: Prisma.XOR<Prisma.ProductUpdateWithoutIncludesInput, Prisma.ProductUncheckedUpdateWithoutIncludesInput>
  create: Prisma.XOR<Prisma.ProductCreateWithoutIncludesInput, Prisma.ProductUncheckedCreateWithoutIncludesInput>
  where?: Prisma.ProductWhereInput
}

export type ProductUpdateToOneWithWhereWithoutIncludesInput = {
  where?: Prisma.ProductWhereInput
  data: Prisma.XOR<Prisma.ProductUpdateWithoutIncludesInput, Prisma.ProductUncheckedUpdateWithoutIncludesInput>
}

export type ProductUpdateWithoutIncludesInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutProductsNestedInput
  images?: Prisma.ProductImageUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUpdateManyWithoutRelatedNestedInput
}

export type ProductUncheckedUpdateWithoutIncludesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.IntFieldUpdateOperationsInput | number
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProductImageUncheckedUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUncheckedUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUncheckedUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUncheckedUpdateManyWithoutRelatedNestedInput
}

export type ProductCreateWithoutRelated_toInput = {
  slug: string
  name: string
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutProductsInput
  images?: Prisma.ProductImageCreateNestedManyWithoutProductInput
  includes?: Prisma.ProductIncludeCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductCreateNestedManyWithoutRelatedInput
}

export type ProductUncheckedCreateWithoutRelated_toInput = {
  id?: number
  slug: string
  name: string
  category_id: number
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  images?: Prisma.ProductImageUncheckedCreateNestedManyWithoutProductInput
  includes?: Prisma.ProductIncludeUncheckedCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemUncheckedCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutRelatedInput
}

export type ProductCreateOrConnectWithoutRelated_toInput = {
  where: Prisma.ProductWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductCreateWithoutRelated_toInput, Prisma.ProductUncheckedCreateWithoutRelated_toInput>
}

export type ProductCreateWithoutRelated_fromInput = {
  slug: string
  name: string
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutProductsInput
  images?: Prisma.ProductImageCreateNestedManyWithoutProductInput
  includes?: Prisma.ProductIncludeCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductCreateNestedManyWithoutProductInput
}

export type ProductUncheckedCreateWithoutRelated_fromInput = {
  id?: number
  slug: string
  name: string
  category_id: number
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  images?: Prisma.ProductImageUncheckedCreateNestedManyWithoutProductInput
  includes?: Prisma.ProductIncludeUncheckedCreateNestedManyWithoutProductInput
  orders?: Prisma.OrderItemUncheckedCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutProductInput
}

export type ProductCreateOrConnectWithoutRelated_fromInput = {
  where: Prisma.ProductWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductCreateWithoutRelated_fromInput, Prisma.ProductUncheckedCreateWithoutRelated_fromInput>
}

export type ProductUpsertWithoutRelated_toInput = {
  update: Prisma.XOR<Prisma.ProductUpdateWithoutRelated_toInput, Prisma.ProductUncheckedUpdateWithoutRelated_toInput>
  create: Prisma.XOR<Prisma.ProductCreateWithoutRelated_toInput, Prisma.ProductUncheckedCreateWithoutRelated_toInput>
  where?: Prisma.ProductWhereInput
}

export type ProductUpdateToOneWithWhereWithoutRelated_toInput = {
  where?: Prisma.ProductWhereInput
  data: Prisma.XOR<Prisma.ProductUpdateWithoutRelated_toInput, Prisma.ProductUncheckedUpdateWithoutRelated_toInput>
}

export type ProductUpdateWithoutRelated_toInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutProductsNestedInput
  images?: Prisma.ProductImageUpdateManyWithoutProductNestedInput
  includes?: Prisma.ProductIncludeUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUpdateManyWithoutRelatedNestedInput
}

export type ProductUncheckedUpdateWithoutRelated_toInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.IntFieldUpdateOperationsInput | number
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProductImageUncheckedUpdateManyWithoutProductNestedInput
  includes?: Prisma.ProductIncludeUncheckedUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUncheckedUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUncheckedUpdateManyWithoutRelatedNestedInput
}

export type ProductUpsertWithoutRelated_fromInput = {
  update: Prisma.XOR<Prisma.ProductUpdateWithoutRelated_fromInput, Prisma.ProductUncheckedUpdateWithoutRelated_fromInput>
  create: Prisma.XOR<Prisma.ProductCreateWithoutRelated_fromInput, Prisma.ProductUncheckedCreateWithoutRelated_fromInput>
  where?: Prisma.ProductWhereInput
}

export type ProductUpdateToOneWithWhereWithoutRelated_fromInput = {
  where?: Prisma.ProductWhereInput
  data: Prisma.XOR<Prisma.ProductUpdateWithoutRelated_fromInput, Prisma.ProductUncheckedUpdateWithoutRelated_fromInput>
}

export type ProductUpdateWithoutRelated_fromInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutProductsNestedInput
  images?: Prisma.ProductImageUpdateManyWithoutProductNestedInput
  includes?: Prisma.ProductIncludeUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUpdateManyWithoutProductNestedInput
}

export type ProductUncheckedUpdateWithoutRelated_fromInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.IntFieldUpdateOperationsInput | number
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProductImageUncheckedUpdateManyWithoutProductNestedInput
  includes?: Prisma.ProductIncludeUncheckedUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUncheckedUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUncheckedUpdateManyWithoutProductNestedInput
}

export type ProductCreateWithoutOrdersInput = {
  slug: string
  name: string
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutProductsInput
  images?: Prisma.ProductImageCreateNestedManyWithoutProductInput
  includes?: Prisma.ProductIncludeCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductCreateNestedManyWithoutRelatedInput
}

export type ProductUncheckedCreateWithoutOrdersInput = {
  id?: number
  slug: string
  name: string
  category_id: number
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
  images?: Prisma.ProductImageUncheckedCreateNestedManyWithoutProductInput
  includes?: Prisma.ProductIncludeUncheckedCreateNestedManyWithoutProductInput
  related_to?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutProductInput
  related_from?: Prisma.RelatedProductUncheckedCreateNestedManyWithoutRelatedInput
}

export type ProductCreateOrConnectWithoutOrdersInput = {
  where: Prisma.ProductWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductCreateWithoutOrdersInput, Prisma.ProductUncheckedCreateWithoutOrdersInput>
}

export type ProductUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.ProductUpdateWithoutOrdersInput, Prisma.ProductUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.ProductCreateWithoutOrdersInput, Prisma.ProductUncheckedCreateWithoutOrdersInput>
  where?: Prisma.ProductWhereInput
}

export type ProductUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.ProductWhereInput
  data: Prisma.XOR<Prisma.ProductUpdateWithoutOrdersInput, Prisma.ProductUncheckedUpdateWithoutOrdersInput>
}

export type ProductUpdateWithoutOrdersInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutProductsNestedInput
  images?: Prisma.ProductImageUpdateManyWithoutProductNestedInput
  includes?: Prisma.ProductIncludeUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUpdateManyWithoutRelatedNestedInput
}

export type ProductUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.IntFieldUpdateOperationsInput | number
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProductImageUncheckedUpdateManyWithoutProductNestedInput
  includes?: Prisma.ProductIncludeUncheckedUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUncheckedUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUncheckedUpdateManyWithoutRelatedNestedInput
}

export type ProductCreateManyCategoryInput = {
  id?: number
  slug: string
  name: string
  new?: boolean
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  description: string
  features: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ProductUpdateWithoutCategoryInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProductImageUpdateManyWithoutProductNestedInput
  includes?: Prisma.ProductIncludeUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUpdateManyWithoutRelatedNestedInput
}

export type ProductUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProductImageUncheckedUpdateManyWithoutProductNestedInput
  includes?: Prisma.ProductIncludeUncheckedUpdateManyWithoutProductNestedInput
  orders?: Prisma.OrderItemUncheckedUpdateManyWithoutProductNestedInput
  related_to?: Prisma.RelatedProductUncheckedUpdateManyWithoutProductNestedInput
  related_from?: Prisma.RelatedProductUncheckedUpdateManyWithoutRelatedNestedInput
}

export type ProductUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  new?: Prisma.BoolFieldUpdateOperationsInput | boolean
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ProductCountOutputType
 */

export type ProductCountOutputType = {
  images: number
  includes: number
  orders: number
  related_to: number
  related_from: number
}

export type ProductCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  images?: boolean | ProductCountOutputTypeCountImagesArgs
  includes?: boolean | ProductCountOutputTypeCountIncludesArgs
  orders?: boolean | ProductCountOutputTypeCountOrdersArgs
  related_to?: boolean | ProductCountOutputTypeCountRelated_toArgs
  related_from?: boolean | ProductCountOutputTypeCountRelated_fromArgs
}

/**
 * ProductCountOutputType without action
 */
export type ProductCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductCountOutputType
   */
  select?: Prisma.ProductCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProductCountOutputType without action
 */
export type ProductCountOutputTypeCountImagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductImageWhereInput
}

/**
 * ProductCountOutputType without action
 */
export type ProductCountOutputTypeCountIncludesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductIncludeWhereInput
}

/**
 * ProductCountOutputType without action
 */
export type ProductCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderItemWhereInput
}

/**
 * ProductCountOutputType without action
 */
export type ProductCountOutputTypeCountRelated_toArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RelatedProductWhereInput
}

/**
 * ProductCountOutputType without action
 */
export type ProductCountOutputTypeCountRelated_fromArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RelatedProductWhereInput
}


export type ProductSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  name?: boolean
  category_id?: boolean
  new?: boolean
  price?: boolean
  description?: boolean
  features?: boolean
  created_at?: boolean
  updated_at?: boolean
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  images?: boolean | Prisma.Product$imagesArgs<ExtArgs>
  includes?: boolean | Prisma.Product$includesArgs<ExtArgs>
  orders?: boolean | Prisma.Product$ordersArgs<ExtArgs>
  related_to?: boolean | Prisma.Product$related_toArgs<ExtArgs>
  related_from?: boolean | Prisma.Product$related_fromArgs<ExtArgs>
  _count?: boolean | Prisma.ProductCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["product"]>

export type ProductSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  name?: boolean
  category_id?: boolean
  new?: boolean
  price?: boolean
  description?: boolean
  features?: boolean
  created_at?: boolean
  updated_at?: boolean
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["product"]>

export type ProductSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  name?: boolean
  category_id?: boolean
  new?: boolean
  price?: boolean
  description?: boolean
  features?: boolean
  created_at?: boolean
  updated_at?: boolean
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["product"]>

export type ProductSelectScalar = {
  id?: boolean
  slug?: boolean
  name?: boolean
  category_id?: boolean
  new?: boolean
  price?: boolean
  description?: boolean
  features?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type ProductOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "slug" | "name" | "category_id" | "new" | "price" | "description" | "features" | "created_at" | "updated_at", ExtArgs["result"]["product"]>
export type ProductInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  images?: boolean | Prisma.Product$imagesArgs<ExtArgs>
  includes?: boolean | Prisma.Product$includesArgs<ExtArgs>
  orders?: boolean | Prisma.Product$ordersArgs<ExtArgs>
  related_to?: boolean | Prisma.Product$related_toArgs<ExtArgs>
  related_from?: boolean | Prisma.Product$related_fromArgs<ExtArgs>
  _count?: boolean | Prisma.ProductCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProductIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}
export type ProductIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}

export type $ProductPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Product"
  objects: {
    category: Prisma.$CategoryPayload<ExtArgs>
    images: Prisma.$ProductImagePayload<ExtArgs>[]
    includes: Prisma.$ProductIncludePayload<ExtArgs>[]
    orders: Prisma.$OrderItemPayload<ExtArgs>[]
    related_to: Prisma.$RelatedProductPayload<ExtArgs>[]
    related_from: Prisma.$RelatedProductPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    slug: string
    name: string
    category_id: number
    new: boolean
    price: runtime.Decimal
    description: string
    features: string
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["product"]>
  composites: {}
}

export type ProductGetPayload<S extends boolean | null | undefined | ProductDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductPayload, S>

export type ProductCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductCountAggregateInputType | true
  }

export interface ProductDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Product'], meta: { name: 'Product' } }
  /**
   * Find zero or one Product that matches the filter.
   * @param {ProductFindUniqueArgs} args - Arguments to find a Product
   * @example
   * // Get one Product
   * const product = await prisma.product.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Product that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductFindUniqueOrThrowArgs} args - Arguments to find a Product
   * @example
   * // Get one Product
   * const product = await prisma.product.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Product that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductFindFirstArgs} args - Arguments to find a Product
   * @example
   * // Get one Product
   * const product = await prisma.product.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Product that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductFindFirstOrThrowArgs} args - Arguments to find a Product
   * @example
   * // Get one Product
   * const product = await prisma.product.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Products that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Products
   * const products = await prisma.product.findMany()
   * 
   * // Get first 10 Products
   * const products = await prisma.product.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productWithIdOnly = await prisma.product.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductFindManyArgs>(args?: Prisma.SelectSubset<T, ProductFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Product.
   * @param {ProductCreateArgs} args - Arguments to create a Product.
   * @example
   * // Create one Product
   * const Product = await prisma.product.create({
   *   data: {
   *     // ... data to create a Product
   *   }
   * })
   * 
   */
  create<T extends ProductCreateArgs>(args: Prisma.SelectSubset<T, ProductCreateArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Products.
   * @param {ProductCreateManyArgs} args - Arguments to create many Products.
   * @example
   * // Create many Products
   * const product = await prisma.product.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Products and returns the data saved in the database.
   * @param {ProductCreateManyAndReturnArgs} args - Arguments to create many Products.
   * @example
   * // Create many Products
   * const product = await prisma.product.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Products and only return the `id`
   * const productWithIdOnly = await prisma.product.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Product.
   * @param {ProductDeleteArgs} args - Arguments to delete one Product.
   * @example
   * // Delete one Product
   * const Product = await prisma.product.delete({
   *   where: {
   *     // ... filter to delete one Product
   *   }
   * })
   * 
   */
  delete<T extends ProductDeleteArgs>(args: Prisma.SelectSubset<T, ProductDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Product.
   * @param {ProductUpdateArgs} args - Arguments to update one Product.
   * @example
   * // Update one Product
   * const product = await prisma.product.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductUpdateArgs>(args: Prisma.SelectSubset<T, ProductUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Products.
   * @param {ProductDeleteManyArgs} args - Arguments to filter Products to delete.
   * @example
   * // Delete a few Products
   * const { count } = await prisma.product.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Products.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Products
   * const product = await prisma.product.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Products and returns the data updated in the database.
   * @param {ProductUpdateManyAndReturnArgs} args - Arguments to update many Products.
   * @example
   * // Update many Products
   * const product = await prisma.product.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Products and only return the `id`
   * const productWithIdOnly = await prisma.product.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Product.
   * @param {ProductUpsertArgs} args - Arguments to update or create a Product.
   * @example
   * // Update or create a Product
   * const product = await prisma.product.upsert({
   *   create: {
   *     // ... data to create a Product
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Product we want to update
   *   }
   * })
   */
  upsert<T extends ProductUpsertArgs>(args: Prisma.SelectSubset<T, ProductUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Products.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductCountArgs} args - Arguments to filter Products to count.
   * @example
   * // Count the number of Products
   * const count = await prisma.product.count({
   *   where: {
   *     // ... the filter for the Products we want to count
   *   }
   * })
  **/
  count<T extends ProductCountArgs>(
    args?: Prisma.Subset<T, ProductCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Product.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductAggregateArgs>(args: Prisma.Subset<T, ProductAggregateArgs>): Prisma.PrismaPromise<GetProductAggregateType<T>>

  /**
   * Group by Product.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductGroupByArgs['orderBy'] }
      : { orderBy?: ProductGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Product model
 */
readonly fields: ProductFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Product.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.CategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  images<T extends Prisma.Product$imagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Product$imagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductImagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  includes<T extends Prisma.Product$includesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Product$includesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductIncludePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  orders<T extends Prisma.Product$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Product$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  related_to<T extends Prisma.Product$related_toArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Product$related_toArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  related_from<T extends Prisma.Product$related_fromArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Product$related_fromArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Product model
 */
export interface ProductFieldRefs {
  readonly id: Prisma.FieldRef<"Product", 'Int'>
  readonly slug: Prisma.FieldRef<"Product", 'String'>
  readonly name: Prisma.FieldRef<"Product", 'String'>
  readonly category_id: Prisma.FieldRef<"Product", 'Int'>
  readonly new: Prisma.FieldRef<"Product", 'Boolean'>
  readonly price: Prisma.FieldRef<"Product", 'Decimal'>
  readonly description: Prisma.FieldRef<"Product", 'String'>
  readonly features: Prisma.FieldRef<"Product", 'String'>
  readonly created_at: Prisma.FieldRef<"Product", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Product", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Product findUnique
 */
export type ProductFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  /**
   * Filter, which Product to fetch.
   */
  where: Prisma.ProductWhereUniqueInput
}

/**
 * Product findUniqueOrThrow
 */
export type ProductFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  /**
   * Filter, which Product to fetch.
   */
  where: Prisma.ProductWhereUniqueInput
}

/**
 * Product findFirst
 */
export type ProductFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  /**
   * Filter, which Product to fetch.
   */
  where?: Prisma.ProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Products to fetch.
   */
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Products.
   */
  cursor?: Prisma.ProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Products from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Products.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Products.
   */
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Product findFirstOrThrow
 */
export type ProductFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  /**
   * Filter, which Product to fetch.
   */
  where?: Prisma.ProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Products to fetch.
   */
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Products.
   */
  cursor?: Prisma.ProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Products from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Products.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Products.
   */
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Product findMany
 */
export type ProductFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  /**
   * Filter, which Products to fetch.
   */
  where?: Prisma.ProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Products to fetch.
   */
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Products.
   */
  cursor?: Prisma.ProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Products from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Products.
   */
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Product create
 */
export type ProductCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  /**
   * The data needed to create a Product.
   */
  data: Prisma.XOR<Prisma.ProductCreateInput, Prisma.ProductUncheckedCreateInput>
}

/**
 * Product createMany
 */
export type ProductCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Products.
   */
  data: Prisma.ProductCreateManyInput | Prisma.ProductCreateManyInput[]
}

/**
 * Product createManyAndReturn
 */
export type ProductCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * The data used to create many Products.
   */
  data: Prisma.ProductCreateManyInput | Prisma.ProductCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Product update
 */
export type ProductUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  /**
   * The data needed to update a Product.
   */
  data: Prisma.XOR<Prisma.ProductUpdateInput, Prisma.ProductUncheckedUpdateInput>
  /**
   * Choose, which Product to update.
   */
  where: Prisma.ProductWhereUniqueInput
}

/**
 * Product updateMany
 */
export type ProductUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Products.
   */
  data: Prisma.XOR<Prisma.ProductUpdateManyMutationInput, Prisma.ProductUncheckedUpdateManyInput>
  /**
   * Filter which Products to update
   */
  where?: Prisma.ProductWhereInput
  /**
   * Limit how many Products to update.
   */
  limit?: number
}

/**
 * Product updateManyAndReturn
 */
export type ProductUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * The data used to update Products.
   */
  data: Prisma.XOR<Prisma.ProductUpdateManyMutationInput, Prisma.ProductUncheckedUpdateManyInput>
  /**
   * Filter which Products to update
   */
  where?: Prisma.ProductWhereInput
  /**
   * Limit how many Products to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Product upsert
 */
export type ProductUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  /**
   * The filter to search for the Product to update in case it exists.
   */
  where: Prisma.ProductWhereUniqueInput
  /**
   * In case the Product found by the `where` argument doesn't exist, create a new Product with this data.
   */
  create: Prisma.XOR<Prisma.ProductCreateInput, Prisma.ProductUncheckedCreateInput>
  /**
   * In case the Product was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductUpdateInput, Prisma.ProductUncheckedUpdateInput>
}

/**
 * Product delete
 */
export type ProductDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  /**
   * Filter which Product to delete.
   */
  where: Prisma.ProductWhereUniqueInput
}

/**
 * Product deleteMany
 */
export type ProductDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Products to delete
   */
  where?: Prisma.ProductWhereInput
  /**
   * Limit how many Products to delete.
   */
  limit?: number
}

/**
 * Product.images
 */
export type Product$imagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductImage
   */
  select?: Prisma.ProductImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductImage
   */
  omit?: Prisma.ProductImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductImageInclude<ExtArgs> | null
  where?: Prisma.ProductImageWhereInput
  orderBy?: Prisma.ProductImageOrderByWithRelationInput | Prisma.ProductImageOrderByWithRelationInput[]
  cursor?: Prisma.ProductImageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductImageScalarFieldEnum | Prisma.ProductImageScalarFieldEnum[]
}

/**
 * Product.includes
 */
export type Product$includesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductInclude
   */
  select?: Prisma.ProductIncludeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductInclude
   */
  omit?: Prisma.ProductIncludeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductIncludeInclude<ExtArgs> | null
  where?: Prisma.ProductIncludeWhereInput
  orderBy?: Prisma.ProductIncludeOrderByWithRelationInput | Prisma.ProductIncludeOrderByWithRelationInput[]
  cursor?: Prisma.ProductIncludeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductIncludeScalarFieldEnum | Prisma.ProductIncludeScalarFieldEnum[]
}

/**
 * Product.orders
 */
export type Product$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderItem
   */
  select?: Prisma.OrderItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderItem
   */
  omit?: Prisma.OrderItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderItemInclude<ExtArgs> | null
  where?: Prisma.OrderItemWhereInput
  orderBy?: Prisma.OrderItemOrderByWithRelationInput | Prisma.OrderItemOrderByWithRelationInput[]
  cursor?: Prisma.OrderItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderItemScalarFieldEnum | Prisma.OrderItemScalarFieldEnum[]
}

/**
 * Product.related_to
 */
export type Product$related_toArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  where?: Prisma.RelatedProductWhereInput
  orderBy?: Prisma.RelatedProductOrderByWithRelationInput | Prisma.RelatedProductOrderByWithRelationInput[]
  cursor?: Prisma.RelatedProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RelatedProductScalarFieldEnum | Prisma.RelatedProductScalarFieldEnum[]
}

/**
 * Product.related_from
 */
export type Product$related_fromArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  where?: Prisma.RelatedProductWhereInput
  orderBy?: Prisma.RelatedProductOrderByWithRelationInput | Prisma.RelatedProductOrderByWithRelationInput[]
  cursor?: Prisma.RelatedProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RelatedProductScalarFieldEnum | Prisma.RelatedProductScalarFieldEnum[]
}

/**
 * Product without action
 */
export type ProductDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
}
