
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RelatedProduct` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RelatedProduct
 * 
 */
export type RelatedProductModel = runtime.Types.Result.DefaultSelection<Prisma.$RelatedProductPayload>

export type AggregateRelatedProduct = {
  _count: RelatedProductCountAggregateOutputType | null
  _avg: RelatedProductAvgAggregateOutputType | null
  _sum: RelatedProductSumAggregateOutputType | null
  _min: RelatedProductMinAggregateOutputType | null
  _max: RelatedProductMaxAggregateOutputType | null
}

export type RelatedProductAvgAggregateOutputType = {
  product_id: number | null
  related_id: number | null
}

export type RelatedProductSumAggregateOutputType = {
  product_id: number | null
  related_id: number | null
}

export type RelatedProductMinAggregateOutputType = {
  product_id: number | null
  related_id: number | null
  mobile: string | null
  tablet: string | null
  desktop: string | null
}

export type RelatedProductMaxAggregateOutputType = {
  product_id: number | null
  related_id: number | null
  mobile: string | null
  tablet: string | null
  desktop: string | null
}

export type RelatedProductCountAggregateOutputType = {
  product_id: number
  related_id: number
  mobile: number
  tablet: number
  desktop: number
  _all: number
}


export type RelatedProductAvgAggregateInputType = {
  product_id?: true
  related_id?: true
}

export type RelatedProductSumAggregateInputType = {
  product_id?: true
  related_id?: true
}

export type RelatedProductMinAggregateInputType = {
  product_id?: true
  related_id?: true
  mobile?: true
  tablet?: true
  desktop?: true
}

export type RelatedProductMaxAggregateInputType = {
  product_id?: true
  related_id?: true
  mobile?: true
  tablet?: true
  desktop?: true
}

export type RelatedProductCountAggregateInputType = {
  product_id?: true
  related_id?: true
  mobile?: true
  tablet?: true
  desktop?: true
  _all?: true
}

export type RelatedProductAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RelatedProduct to aggregate.
   */
  where?: Prisma.RelatedProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RelatedProducts to fetch.
   */
  orderBy?: Prisma.RelatedProductOrderByWithRelationInput | Prisma.RelatedProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RelatedProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RelatedProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RelatedProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RelatedProducts
  **/
  _count?: true | RelatedProductCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RelatedProductAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RelatedProductSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RelatedProductMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RelatedProductMaxAggregateInputType
}

export type GetRelatedProductAggregateType<T extends RelatedProductAggregateArgs> = {
      [P in keyof T & keyof AggregateRelatedProduct]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRelatedProduct[P]>
    : Prisma.GetScalarType<T[P], AggregateRelatedProduct[P]>
}




export type RelatedProductGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RelatedProductWhereInput
  orderBy?: Prisma.RelatedProductOrderByWithAggregationInput | Prisma.RelatedProductOrderByWithAggregationInput[]
  by: Prisma.RelatedProductScalarFieldEnum[] | Prisma.RelatedProductScalarFieldEnum
  having?: Prisma.RelatedProductScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RelatedProductCountAggregateInputType | true
  _avg?: RelatedProductAvgAggregateInputType
  _sum?: RelatedProductSumAggregateInputType
  _min?: RelatedProductMinAggregateInputType
  _max?: RelatedProductMaxAggregateInputType
}

export type RelatedProductGroupByOutputType = {
  product_id: number
  related_id: number
  mobile: string
  tablet: string
  desktop: string
  _count: RelatedProductCountAggregateOutputType | null
  _avg: RelatedProductAvgAggregateOutputType | null
  _sum: RelatedProductSumAggregateOutputType | null
  _min: RelatedProductMinAggregateOutputType | null
  _max: RelatedProductMaxAggregateOutputType | null
}

type GetRelatedProductGroupByPayload<T extends RelatedProductGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RelatedProductGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RelatedProductGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RelatedProductGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RelatedProductGroupByOutputType[P]>
      }
    >
  >



export type RelatedProductWhereInput = {
  AND?: Prisma.RelatedProductWhereInput | Prisma.RelatedProductWhereInput[]
  OR?: Prisma.RelatedProductWhereInput[]
  NOT?: Prisma.RelatedProductWhereInput | Prisma.RelatedProductWhereInput[]
  product_id?: Prisma.IntFilter<"RelatedProduct"> | number
  related_id?: Prisma.IntFilter<"RelatedProduct"> | number
  mobile?: Prisma.StringFilter<"RelatedProduct"> | string
  tablet?: Prisma.StringFilter<"RelatedProduct"> | string
  desktop?: Prisma.StringFilter<"RelatedProduct"> | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  related?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type RelatedProductOrderByWithRelationInput = {
  product_id?: Prisma.SortOrder
  related_id?: Prisma.SortOrder
  mobile?: Prisma.SortOrder
  tablet?: Prisma.SortOrder
  desktop?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
  related?: Prisma.ProductOrderByWithRelationInput
}

export type RelatedProductWhereUniqueInput = Prisma.AtLeast<{
  product_id_related_id?: Prisma.RelatedProductProduct_idRelated_idCompoundUniqueInput
  AND?: Prisma.RelatedProductWhereInput | Prisma.RelatedProductWhereInput[]
  OR?: Prisma.RelatedProductWhereInput[]
  NOT?: Prisma.RelatedProductWhereInput | Prisma.RelatedProductWhereInput[]
  product_id?: Prisma.IntFilter<"RelatedProduct"> | number
  related_id?: Prisma.IntFilter<"RelatedProduct"> | number
  mobile?: Prisma.StringFilter<"RelatedProduct"> | string
  tablet?: Prisma.StringFilter<"RelatedProduct"> | string
  desktop?: Prisma.StringFilter<"RelatedProduct"> | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  related?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "product_id_related_id">

export type RelatedProductOrderByWithAggregationInput = {
  product_id?: Prisma.SortOrder
  related_id?: Prisma.SortOrder
  mobile?: Prisma.SortOrder
  tablet?: Prisma.SortOrder
  desktop?: Prisma.SortOrder
  _count?: Prisma.RelatedProductCountOrderByAggregateInput
  _avg?: Prisma.RelatedProductAvgOrderByAggregateInput
  _max?: Prisma.RelatedProductMaxOrderByAggregateInput
  _min?: Prisma.RelatedProductMinOrderByAggregateInput
  _sum?: Prisma.RelatedProductSumOrderByAggregateInput
}

export type RelatedProductScalarWhereWithAggregatesInput = {
  AND?: Prisma.RelatedProductScalarWhereWithAggregatesInput | Prisma.RelatedProductScalarWhereWithAggregatesInput[]
  OR?: Prisma.RelatedProductScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RelatedProductScalarWhereWithAggregatesInput | Prisma.RelatedProductScalarWhereWithAggregatesInput[]
  product_id?: Prisma.IntWithAggregatesFilter<"RelatedProduct"> | number
  related_id?: Prisma.IntWithAggregatesFilter<"RelatedProduct"> | number
  mobile?: Prisma.StringWithAggregatesFilter<"RelatedProduct"> | string
  tablet?: Prisma.StringWithAggregatesFilter<"RelatedProduct"> | string
  desktop?: Prisma.StringWithAggregatesFilter<"RelatedProduct"> | string
}

export type RelatedProductCreateInput = {
  mobile: string
  tablet: string
  desktop: string
  product: Prisma.ProductCreateNestedOneWithoutRelated_toInput
  related: Prisma.ProductCreateNestedOneWithoutRelated_fromInput
}

export type RelatedProductUncheckedCreateInput = {
  product_id: number
  related_id: number
  mobile: string
  tablet: string
  desktop: string
}

export type RelatedProductUpdateInput = {
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  tablet?: Prisma.StringFieldUpdateOperationsInput | string
  desktop?: Prisma.StringFieldUpdateOperationsInput | string
  product?: Prisma.ProductUpdateOneRequiredWithoutRelated_toNestedInput
  related?: Prisma.ProductUpdateOneRequiredWithoutRelated_fromNestedInput
}

export type RelatedProductUncheckedUpdateInput = {
  product_id?: Prisma.IntFieldUpdateOperationsInput | number
  related_id?: Prisma.IntFieldUpdateOperationsInput | number
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  tablet?: Prisma.StringFieldUpdateOperationsInput | string
  desktop?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RelatedProductCreateManyInput = {
  product_id: number
  related_id: number
  mobile: string
  tablet: string
  desktop: string
}

export type RelatedProductUpdateManyMutationInput = {
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  tablet?: Prisma.StringFieldUpdateOperationsInput | string
  desktop?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RelatedProductUncheckedUpdateManyInput = {
  product_id?: Prisma.IntFieldUpdateOperationsInput | number
  related_id?: Prisma.IntFieldUpdateOperationsInput | number
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  tablet?: Prisma.StringFieldUpdateOperationsInput | string
  desktop?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RelatedProductListRelationFilter = {
  every?: Prisma.RelatedProductWhereInput
  some?: Prisma.RelatedProductWhereInput
  none?: Prisma.RelatedProductWhereInput
}

export type RelatedProductOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RelatedProductProduct_idRelated_idCompoundUniqueInput = {
  product_id: number
  related_id: number
}

export type RelatedProductCountOrderByAggregateInput = {
  product_id?: Prisma.SortOrder
  related_id?: Prisma.SortOrder
  mobile?: Prisma.SortOrder
  tablet?: Prisma.SortOrder
  desktop?: Prisma.SortOrder
}

export type RelatedProductAvgOrderByAggregateInput = {
  product_id?: Prisma.SortOrder
  related_id?: Prisma.SortOrder
}

export type RelatedProductMaxOrderByAggregateInput = {
  product_id?: Prisma.SortOrder
  related_id?: Prisma.SortOrder
  mobile?: Prisma.SortOrder
  tablet?: Prisma.SortOrder
  desktop?: Prisma.SortOrder
}

export type RelatedProductMinOrderByAggregateInput = {
  product_id?: Prisma.SortOrder
  related_id?: Prisma.SortOrder
  mobile?: Prisma.SortOrder
  tablet?: Prisma.SortOrder
  desktop?: Prisma.SortOrder
}

export type RelatedProductSumOrderByAggregateInput = {
  product_id?: Prisma.SortOrder
  related_id?: Prisma.SortOrder
}

export type RelatedProductCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.RelatedProductCreateWithoutProductInput, Prisma.RelatedProductUncheckedCreateWithoutProductInput> | Prisma.RelatedProductCreateWithoutProductInput[] | Prisma.RelatedProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.RelatedProductCreateOrConnectWithoutProductInput | Prisma.RelatedProductCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.RelatedProductCreateManyProductInputEnvelope
  connect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
}

export type RelatedProductCreateNestedManyWithoutRelatedInput = {
  create?: Prisma.XOR<Prisma.RelatedProductCreateWithoutRelatedInput, Prisma.RelatedProductUncheckedCreateWithoutRelatedInput> | Prisma.RelatedProductCreateWithoutRelatedInput[] | Prisma.RelatedProductUncheckedCreateWithoutRelatedInput[]
  connectOrCreate?: Prisma.RelatedProductCreateOrConnectWithoutRelatedInput | Prisma.RelatedProductCreateOrConnectWithoutRelatedInput[]
  createMany?: Prisma.RelatedProductCreateManyRelatedInputEnvelope
  connect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
}

export type RelatedProductUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.RelatedProductCreateWithoutProductInput, Prisma.RelatedProductUncheckedCreateWithoutProductInput> | Prisma.RelatedProductCreateWithoutProductInput[] | Prisma.RelatedProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.RelatedProductCreateOrConnectWithoutProductInput | Prisma.RelatedProductCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.RelatedProductCreateManyProductInputEnvelope
  connect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
}

export type RelatedProductUncheckedCreateNestedManyWithoutRelatedInput = {
  create?: Prisma.XOR<Prisma.RelatedProductCreateWithoutRelatedInput, Prisma.RelatedProductUncheckedCreateWithoutRelatedInput> | Prisma.RelatedProductCreateWithoutRelatedInput[] | Prisma.RelatedProductUncheckedCreateWithoutRelatedInput[]
  connectOrCreate?: Prisma.RelatedProductCreateOrConnectWithoutRelatedInput | Prisma.RelatedProductCreateOrConnectWithoutRelatedInput[]
  createMany?: Prisma.RelatedProductCreateManyRelatedInputEnvelope
  connect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
}

export type RelatedProductUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.RelatedProductCreateWithoutProductInput, Prisma.RelatedProductUncheckedCreateWithoutProductInput> | Prisma.RelatedProductCreateWithoutProductInput[] | Prisma.RelatedProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.RelatedProductCreateOrConnectWithoutProductInput | Prisma.RelatedProductCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.RelatedProductUpsertWithWhereUniqueWithoutProductInput | Prisma.RelatedProductUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.RelatedProductCreateManyProductInputEnvelope
  set?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  disconnect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  delete?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  connect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  update?: Prisma.RelatedProductUpdateWithWhereUniqueWithoutProductInput | Prisma.RelatedProductUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.RelatedProductUpdateManyWithWhereWithoutProductInput | Prisma.RelatedProductUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.RelatedProductScalarWhereInput | Prisma.RelatedProductScalarWhereInput[]
}

export type RelatedProductUpdateManyWithoutRelatedNestedInput = {
  create?: Prisma.XOR<Prisma.RelatedProductCreateWithoutRelatedInput, Prisma.RelatedProductUncheckedCreateWithoutRelatedInput> | Prisma.RelatedProductCreateWithoutRelatedInput[] | Prisma.RelatedProductUncheckedCreateWithoutRelatedInput[]
  connectOrCreate?: Prisma.RelatedProductCreateOrConnectWithoutRelatedInput | Prisma.RelatedProductCreateOrConnectWithoutRelatedInput[]
  upsert?: Prisma.RelatedProductUpsertWithWhereUniqueWithoutRelatedInput | Prisma.RelatedProductUpsertWithWhereUniqueWithoutRelatedInput[]
  createMany?: Prisma.RelatedProductCreateManyRelatedInputEnvelope
  set?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  disconnect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  delete?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  connect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  update?: Prisma.RelatedProductUpdateWithWhereUniqueWithoutRelatedInput | Prisma.RelatedProductUpdateWithWhereUniqueWithoutRelatedInput[]
  updateMany?: Prisma.RelatedProductUpdateManyWithWhereWithoutRelatedInput | Prisma.RelatedProductUpdateManyWithWhereWithoutRelatedInput[]
  deleteMany?: Prisma.RelatedProductScalarWhereInput | Prisma.RelatedProductScalarWhereInput[]
}

export type RelatedProductUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.RelatedProductCreateWithoutProductInput, Prisma.RelatedProductUncheckedCreateWithoutProductInput> | Prisma.RelatedProductCreateWithoutProductInput[] | Prisma.RelatedProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.RelatedProductCreateOrConnectWithoutProductInput | Prisma.RelatedProductCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.RelatedProductUpsertWithWhereUniqueWithoutProductInput | Prisma.RelatedProductUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.RelatedProductCreateManyProductInputEnvelope
  set?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  disconnect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  delete?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  connect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  update?: Prisma.RelatedProductUpdateWithWhereUniqueWithoutProductInput | Prisma.RelatedProductUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.RelatedProductUpdateManyWithWhereWithoutProductInput | Prisma.RelatedProductUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.RelatedProductScalarWhereInput | Prisma.RelatedProductScalarWhereInput[]
}

export type RelatedProductUncheckedUpdateManyWithoutRelatedNestedInput = {
  create?: Prisma.XOR<Prisma.RelatedProductCreateWithoutRelatedInput, Prisma.RelatedProductUncheckedCreateWithoutRelatedInput> | Prisma.RelatedProductCreateWithoutRelatedInput[] | Prisma.RelatedProductUncheckedCreateWithoutRelatedInput[]
  connectOrCreate?: Prisma.RelatedProductCreateOrConnectWithoutRelatedInput | Prisma.RelatedProductCreateOrConnectWithoutRelatedInput[]
  upsert?: Prisma.RelatedProductUpsertWithWhereUniqueWithoutRelatedInput | Prisma.RelatedProductUpsertWithWhereUniqueWithoutRelatedInput[]
  createMany?: Prisma.RelatedProductCreateManyRelatedInputEnvelope
  set?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  disconnect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  delete?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  connect?: Prisma.RelatedProductWhereUniqueInput | Prisma.RelatedProductWhereUniqueInput[]
  update?: Prisma.RelatedProductUpdateWithWhereUniqueWithoutRelatedInput | Prisma.RelatedProductUpdateWithWhereUniqueWithoutRelatedInput[]
  updateMany?: Prisma.RelatedProductUpdateManyWithWhereWithoutRelatedInput | Prisma.RelatedProductUpdateManyWithWhereWithoutRelatedInput[]
  deleteMany?: Prisma.RelatedProductScalarWhereInput | Prisma.RelatedProductScalarWhereInput[]
}

export type RelatedProductCreateWithoutProductInput = {
  mobile: string
  tablet: string
  desktop: string
  related: Prisma.ProductCreateNestedOneWithoutRelated_fromInput
}

export type RelatedProductUncheckedCreateWithoutProductInput = {
  related_id: number
  mobile: string
  tablet: string
  desktop: string
}

export type RelatedProductCreateOrConnectWithoutProductInput = {
  where: Prisma.RelatedProductWhereUniqueInput
  create: Prisma.XOR<Prisma.RelatedProductCreateWithoutProductInput, Prisma.RelatedProductUncheckedCreateWithoutProductInput>
}

export type RelatedProductCreateManyProductInputEnvelope = {
  data: Prisma.RelatedProductCreateManyProductInput | Prisma.RelatedProductCreateManyProductInput[]
}

export type RelatedProductCreateWithoutRelatedInput = {
  mobile: string
  tablet: string
  desktop: string
  product: Prisma.ProductCreateNestedOneWithoutRelated_toInput
}

export type RelatedProductUncheckedCreateWithoutRelatedInput = {
  product_id: number
  mobile: string
  tablet: string
  desktop: string
}

export type RelatedProductCreateOrConnectWithoutRelatedInput = {
  where: Prisma.RelatedProductWhereUniqueInput
  create: Prisma.XOR<Prisma.RelatedProductCreateWithoutRelatedInput, Prisma.RelatedProductUncheckedCreateWithoutRelatedInput>
}

export type RelatedProductCreateManyRelatedInputEnvelope = {
  data: Prisma.RelatedProductCreateManyRelatedInput | Prisma.RelatedProductCreateManyRelatedInput[]
}

export type RelatedProductUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.RelatedProductWhereUniqueInput
  update: Prisma.XOR<Prisma.RelatedProductUpdateWithoutProductInput, Prisma.RelatedProductUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.RelatedProductCreateWithoutProductInput, Prisma.RelatedProductUncheckedCreateWithoutProductInput>
}

export type RelatedProductUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.RelatedProductWhereUniqueInput
  data: Prisma.XOR<Prisma.RelatedProductUpdateWithoutProductInput, Prisma.RelatedProductUncheckedUpdateWithoutProductInput>
}

export type RelatedProductUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.RelatedProductScalarWhereInput
  data: Prisma.XOR<Prisma.RelatedProductUpdateManyMutationInput, Prisma.RelatedProductUncheckedUpdateManyWithoutProductInput>
}

export type RelatedProductScalarWhereInput = {
  AND?: Prisma.RelatedProductScalarWhereInput | Prisma.RelatedProductScalarWhereInput[]
  OR?: Prisma.RelatedProductScalarWhereInput[]
  NOT?: Prisma.RelatedProductScalarWhereInput | Prisma.RelatedProductScalarWhereInput[]
  product_id?: Prisma.IntFilter<"RelatedProduct"> | number
  related_id?: Prisma.IntFilter<"RelatedProduct"> | number
  mobile?: Prisma.StringFilter<"RelatedProduct"> | string
  tablet?: Prisma.StringFilter<"RelatedProduct"> | string
  desktop?: Prisma.StringFilter<"RelatedProduct"> | string
}

export type RelatedProductUpsertWithWhereUniqueWithoutRelatedInput = {
  where: Prisma.RelatedProductWhereUniqueInput
  update: Prisma.XOR<Prisma.RelatedProductUpdateWithoutRelatedInput, Prisma.RelatedProductUncheckedUpdateWithoutRelatedInput>
  create: Prisma.XOR<Prisma.RelatedProductCreateWithoutRelatedInput, Prisma.RelatedProductUncheckedCreateWithoutRelatedInput>
}

export type RelatedProductUpdateWithWhereUniqueWithoutRelatedInput = {
  where: Prisma.RelatedProductWhereUniqueInput
  data: Prisma.XOR<Prisma.RelatedProductUpdateWithoutRelatedInput, Prisma.RelatedProductUncheckedUpdateWithoutRelatedInput>
}

export type RelatedProductUpdateManyWithWhereWithoutRelatedInput = {
  where: Prisma.RelatedProductScalarWhereInput
  data: Prisma.XOR<Prisma.RelatedProductUpdateManyMutationInput, Prisma.RelatedProductUncheckedUpdateManyWithoutRelatedInput>
}

export type RelatedProductCreateManyProductInput = {
  related_id: number
  mobile: string
  tablet: string
  desktop: string
}

export type RelatedProductCreateManyRelatedInput = {
  product_id: number
  mobile: string
  tablet: string
  desktop: string
}

export type RelatedProductUpdateWithoutProductInput = {
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  tablet?: Prisma.StringFieldUpdateOperationsInput | string
  desktop?: Prisma.StringFieldUpdateOperationsInput | string
  related?: Prisma.ProductUpdateOneRequiredWithoutRelated_fromNestedInput
}

export type RelatedProductUncheckedUpdateWithoutProductInput = {
  related_id?: Prisma.IntFieldUpdateOperationsInput | number
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  tablet?: Prisma.StringFieldUpdateOperationsInput | string
  desktop?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RelatedProductUncheckedUpdateManyWithoutProductInput = {
  related_id?: Prisma.IntFieldUpdateOperationsInput | number
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  tablet?: Prisma.StringFieldUpdateOperationsInput | string
  desktop?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RelatedProductUpdateWithoutRelatedInput = {
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  tablet?: Prisma.StringFieldUpdateOperationsInput | string
  desktop?: Prisma.StringFieldUpdateOperationsInput | string
  product?: Prisma.ProductUpdateOneRequiredWithoutRelated_toNestedInput
}

export type RelatedProductUncheckedUpdateWithoutRelatedInput = {
  product_id?: Prisma.IntFieldUpdateOperationsInput | number
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  tablet?: Prisma.StringFieldUpdateOperationsInput | string
  desktop?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RelatedProductUncheckedUpdateManyWithoutRelatedInput = {
  product_id?: Prisma.IntFieldUpdateOperationsInput | number
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  tablet?: Prisma.StringFieldUpdateOperationsInput | string
  desktop?: Prisma.StringFieldUpdateOperationsInput | string
}



export type RelatedProductSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  product_id?: boolean
  related_id?: boolean
  mobile?: boolean
  tablet?: boolean
  desktop?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  related?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["relatedProduct"]>

export type RelatedProductSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  product_id?: boolean
  related_id?: boolean
  mobile?: boolean
  tablet?: boolean
  desktop?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  related?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["relatedProduct"]>

export type RelatedProductSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  product_id?: boolean
  related_id?: boolean
  mobile?: boolean
  tablet?: boolean
  desktop?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  related?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["relatedProduct"]>

export type RelatedProductSelectScalar = {
  product_id?: boolean
  related_id?: boolean
  mobile?: boolean
  tablet?: boolean
  desktop?: boolean
}

export type RelatedProductOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"product_id" | "related_id" | "mobile" | "tablet" | "desktop", ExtArgs["result"]["relatedProduct"]>
export type RelatedProductInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  related?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type RelatedProductIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  related?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type RelatedProductIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  related?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $RelatedProductPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RelatedProduct"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
    related: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    product_id: number
    related_id: number
    mobile: string
    tablet: string
    desktop: string
  }, ExtArgs["result"]["relatedProduct"]>
  composites: {}
}

export type RelatedProductGetPayload<S extends boolean | null | undefined | RelatedProductDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload, S>

export type RelatedProductCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RelatedProductFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RelatedProductCountAggregateInputType | true
  }

export interface RelatedProductDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RelatedProduct'], meta: { name: 'RelatedProduct' } }
  /**
   * Find zero or one RelatedProduct that matches the filter.
   * @param {RelatedProductFindUniqueArgs} args - Arguments to find a RelatedProduct
   * @example
   * // Get one RelatedProduct
   * const relatedProduct = await prisma.relatedProduct.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RelatedProductFindUniqueArgs>(args: Prisma.SelectSubset<T, RelatedProductFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RelatedProductClient<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RelatedProduct that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RelatedProductFindUniqueOrThrowArgs} args - Arguments to find a RelatedProduct
   * @example
   * // Get one RelatedProduct
   * const relatedProduct = await prisma.relatedProduct.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RelatedProductFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RelatedProductFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RelatedProductClient<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RelatedProduct that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RelatedProductFindFirstArgs} args - Arguments to find a RelatedProduct
   * @example
   * // Get one RelatedProduct
   * const relatedProduct = await prisma.relatedProduct.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RelatedProductFindFirstArgs>(args?: Prisma.SelectSubset<T, RelatedProductFindFirstArgs<ExtArgs>>): Prisma.Prisma__RelatedProductClient<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RelatedProduct that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RelatedProductFindFirstOrThrowArgs} args - Arguments to find a RelatedProduct
   * @example
   * // Get one RelatedProduct
   * const relatedProduct = await prisma.relatedProduct.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RelatedProductFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RelatedProductFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RelatedProductClient<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RelatedProducts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RelatedProductFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RelatedProducts
   * const relatedProducts = await prisma.relatedProduct.findMany()
   * 
   * // Get first 10 RelatedProducts
   * const relatedProducts = await prisma.relatedProduct.findMany({ take: 10 })
   * 
   * // Only select the `product_id`
   * const relatedProductWithProduct_idOnly = await prisma.relatedProduct.findMany({ select: { product_id: true } })
   * 
   */
  findMany<T extends RelatedProductFindManyArgs>(args?: Prisma.SelectSubset<T, RelatedProductFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RelatedProduct.
   * @param {RelatedProductCreateArgs} args - Arguments to create a RelatedProduct.
   * @example
   * // Create one RelatedProduct
   * const RelatedProduct = await prisma.relatedProduct.create({
   *   data: {
   *     // ... data to create a RelatedProduct
   *   }
   * })
   * 
   */
  create<T extends RelatedProductCreateArgs>(args: Prisma.SelectSubset<T, RelatedProductCreateArgs<ExtArgs>>): Prisma.Prisma__RelatedProductClient<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RelatedProducts.
   * @param {RelatedProductCreateManyArgs} args - Arguments to create many RelatedProducts.
   * @example
   * // Create many RelatedProducts
   * const relatedProduct = await prisma.relatedProduct.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RelatedProductCreateManyArgs>(args?: Prisma.SelectSubset<T, RelatedProductCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RelatedProducts and returns the data saved in the database.
   * @param {RelatedProductCreateManyAndReturnArgs} args - Arguments to create many RelatedProducts.
   * @example
   * // Create many RelatedProducts
   * const relatedProduct = await prisma.relatedProduct.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RelatedProducts and only return the `product_id`
   * const relatedProductWithProduct_idOnly = await prisma.relatedProduct.createManyAndReturn({
   *   select: { product_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RelatedProductCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RelatedProductCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RelatedProduct.
   * @param {RelatedProductDeleteArgs} args - Arguments to delete one RelatedProduct.
   * @example
   * // Delete one RelatedProduct
   * const RelatedProduct = await prisma.relatedProduct.delete({
   *   where: {
   *     // ... filter to delete one RelatedProduct
   *   }
   * })
   * 
   */
  delete<T extends RelatedProductDeleteArgs>(args: Prisma.SelectSubset<T, RelatedProductDeleteArgs<ExtArgs>>): Prisma.Prisma__RelatedProductClient<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RelatedProduct.
   * @param {RelatedProductUpdateArgs} args - Arguments to update one RelatedProduct.
   * @example
   * // Update one RelatedProduct
   * const relatedProduct = await prisma.relatedProduct.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RelatedProductUpdateArgs>(args: Prisma.SelectSubset<T, RelatedProductUpdateArgs<ExtArgs>>): Prisma.Prisma__RelatedProductClient<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RelatedProducts.
   * @param {RelatedProductDeleteManyArgs} args - Arguments to filter RelatedProducts to delete.
   * @example
   * // Delete a few RelatedProducts
   * const { count } = await prisma.relatedProduct.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RelatedProductDeleteManyArgs>(args?: Prisma.SelectSubset<T, RelatedProductDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RelatedProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RelatedProductUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RelatedProducts
   * const relatedProduct = await prisma.relatedProduct.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RelatedProductUpdateManyArgs>(args: Prisma.SelectSubset<T, RelatedProductUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RelatedProducts and returns the data updated in the database.
   * @param {RelatedProductUpdateManyAndReturnArgs} args - Arguments to update many RelatedProducts.
   * @example
   * // Update many RelatedProducts
   * const relatedProduct = await prisma.relatedProduct.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RelatedProducts and only return the `product_id`
   * const relatedProductWithProduct_idOnly = await prisma.relatedProduct.updateManyAndReturn({
   *   select: { product_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RelatedProductUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RelatedProductUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RelatedProduct.
   * @param {RelatedProductUpsertArgs} args - Arguments to update or create a RelatedProduct.
   * @example
   * // Update or create a RelatedProduct
   * const relatedProduct = await prisma.relatedProduct.upsert({
   *   create: {
   *     // ... data to create a RelatedProduct
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RelatedProduct we want to update
   *   }
   * })
   */
  upsert<T extends RelatedProductUpsertArgs>(args: Prisma.SelectSubset<T, RelatedProductUpsertArgs<ExtArgs>>): Prisma.Prisma__RelatedProductClient<runtime.Types.Result.GetResult<Prisma.$RelatedProductPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RelatedProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RelatedProductCountArgs} args - Arguments to filter RelatedProducts to count.
   * @example
   * // Count the number of RelatedProducts
   * const count = await prisma.relatedProduct.count({
   *   where: {
   *     // ... the filter for the RelatedProducts we want to count
   *   }
   * })
  **/
  count<T extends RelatedProductCountArgs>(
    args?: Prisma.Subset<T, RelatedProductCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RelatedProductCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RelatedProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RelatedProductAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RelatedProductAggregateArgs>(args: Prisma.Subset<T, RelatedProductAggregateArgs>): Prisma.PrismaPromise<GetRelatedProductAggregateType<T>>

  /**
   * Group by RelatedProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RelatedProductGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RelatedProductGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RelatedProductGroupByArgs['orderBy'] }
      : { orderBy?: RelatedProductGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RelatedProductGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRelatedProductGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RelatedProduct model
 */
readonly fields: RelatedProductFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RelatedProduct.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RelatedProductClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  related<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RelatedProduct model
 */
export interface RelatedProductFieldRefs {
  readonly product_id: Prisma.FieldRef<"RelatedProduct", 'Int'>
  readonly related_id: Prisma.FieldRef<"RelatedProduct", 'Int'>
  readonly mobile: Prisma.FieldRef<"RelatedProduct", 'String'>
  readonly tablet: Prisma.FieldRef<"RelatedProduct", 'String'>
  readonly desktop: Prisma.FieldRef<"RelatedProduct", 'String'>
}
    

// Custom InputTypes
/**
 * RelatedProduct findUnique
 */
export type RelatedProductFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  /**
   * Filter, which RelatedProduct to fetch.
   */
  where: Prisma.RelatedProductWhereUniqueInput
}

/**
 * RelatedProduct findUniqueOrThrow
 */
export type RelatedProductFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  /**
   * Filter, which RelatedProduct to fetch.
   */
  where: Prisma.RelatedProductWhereUniqueInput
}

/**
 * RelatedProduct findFirst
 */
export type RelatedProductFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  /**
   * Filter, which RelatedProduct to fetch.
   */
  where?: Prisma.RelatedProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RelatedProducts to fetch.
   */
  orderBy?: Prisma.RelatedProductOrderByWithRelationInput | Prisma.RelatedProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RelatedProducts.
   */
  cursor?: Prisma.RelatedProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RelatedProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RelatedProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RelatedProducts.
   */
  distinct?: Prisma.RelatedProductScalarFieldEnum | Prisma.RelatedProductScalarFieldEnum[]
}

/**
 * RelatedProduct findFirstOrThrow
 */
export type RelatedProductFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  /**
   * Filter, which RelatedProduct to fetch.
   */
  where?: Prisma.RelatedProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RelatedProducts to fetch.
   */
  orderBy?: Prisma.RelatedProductOrderByWithRelationInput | Prisma.RelatedProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RelatedProducts.
   */
  cursor?: Prisma.RelatedProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RelatedProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RelatedProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RelatedProducts.
   */
  distinct?: Prisma.RelatedProductScalarFieldEnum | Prisma.RelatedProductScalarFieldEnum[]
}

/**
 * RelatedProduct findMany
 */
export type RelatedProductFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  /**
   * Filter, which RelatedProducts to fetch.
   */
  where?: Prisma.RelatedProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RelatedProducts to fetch.
   */
  orderBy?: Prisma.RelatedProductOrderByWithRelationInput | Prisma.RelatedProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RelatedProducts.
   */
  cursor?: Prisma.RelatedProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RelatedProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RelatedProducts.
   */
  skip?: number
  distinct?: Prisma.RelatedProductScalarFieldEnum | Prisma.RelatedProductScalarFieldEnum[]
}

/**
 * RelatedProduct create
 */
export type RelatedProductCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  /**
   * The data needed to create a RelatedProduct.
   */
  data: Prisma.XOR<Prisma.RelatedProductCreateInput, Prisma.RelatedProductUncheckedCreateInput>
}

/**
 * RelatedProduct createMany
 */
export type RelatedProductCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RelatedProducts.
   */
  data: Prisma.RelatedProductCreateManyInput | Prisma.RelatedProductCreateManyInput[]
}

/**
 * RelatedProduct createManyAndReturn
 */
export type RelatedProductCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * The data used to create many RelatedProducts.
   */
  data: Prisma.RelatedProductCreateManyInput | Prisma.RelatedProductCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RelatedProduct update
 */
export type RelatedProductUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  /**
   * The data needed to update a RelatedProduct.
   */
  data: Prisma.XOR<Prisma.RelatedProductUpdateInput, Prisma.RelatedProductUncheckedUpdateInput>
  /**
   * Choose, which RelatedProduct to update.
   */
  where: Prisma.RelatedProductWhereUniqueInput
}

/**
 * RelatedProduct updateMany
 */
export type RelatedProductUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RelatedProducts.
   */
  data: Prisma.XOR<Prisma.RelatedProductUpdateManyMutationInput, Prisma.RelatedProductUncheckedUpdateManyInput>
  /**
   * Filter which RelatedProducts to update
   */
  where?: Prisma.RelatedProductWhereInput
  /**
   * Limit how many RelatedProducts to update.
   */
  limit?: number
}

/**
 * RelatedProduct updateManyAndReturn
 */
export type RelatedProductUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * The data used to update RelatedProducts.
   */
  data: Prisma.XOR<Prisma.RelatedProductUpdateManyMutationInput, Prisma.RelatedProductUncheckedUpdateManyInput>
  /**
   * Filter which RelatedProducts to update
   */
  where?: Prisma.RelatedProductWhereInput
  /**
   * Limit how many RelatedProducts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RelatedProduct upsert
 */
export type RelatedProductUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  /**
   * The filter to search for the RelatedProduct to update in case it exists.
   */
  where: Prisma.RelatedProductWhereUniqueInput
  /**
   * In case the RelatedProduct found by the `where` argument doesn't exist, create a new RelatedProduct with this data.
   */
  create: Prisma.XOR<Prisma.RelatedProductCreateInput, Prisma.RelatedProductUncheckedCreateInput>
  /**
   * In case the RelatedProduct was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RelatedProductUpdateInput, Prisma.RelatedProductUncheckedUpdateInput>
}

/**
 * RelatedProduct delete
 */
export type RelatedProductDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
  /**
   * Filter which RelatedProduct to delete.
   */
  where: Prisma.RelatedProductWhereUniqueInput
}

/**
 * RelatedProduct deleteMany
 */
export type RelatedProductDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RelatedProducts to delete
   */
  where?: Prisma.RelatedProductWhereInput
  /**
   * Limit how many RelatedProducts to delete.
   */
  limit?: number
}

/**
 * RelatedProduct without action
 */
export type RelatedProductDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RelatedProduct
   */
  select?: Prisma.RelatedProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RelatedProduct
   */
  omit?: Prisma.RelatedProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RelatedProductInclude<ExtArgs> | null
}
