/* !!! This is code generated by a script. Do not edit directly. !!! */
/** biome-ignore-all assist/source/organizeImports: generated file */
/** biome-ignore-all lint: generated file */
/* eslint-disable */
// @ts-nocheck
/*
 * This is a barrel export file for all the icons in this directory as React components.
 *
 * 🟢 You can import this file directly.
 * Generated on: Thu Feb 19 09:19:11 PM WAT 2026
 */
export { default as IconArrowRight } from "./arrow-right.svg?react";
export { default as IconCart } from "./cart.svg?react";
export { default as IconCashOnDelivery } from "./cash-on-delivery.svg?react";
export { default as IconFacebook } from "./facebook.svg?react";
export { default as IconGithub } from "./github.svg?react";
export { default as IconHamburger } from "./hamburger.svg?react";
export { default as IconInstagram } from "./instagram.svg?react";
export { default as IconLinkedIn } from "./linked-in.svg?react";
export { default as IconLogo } from "./logo.svg?react";
export { default as IconOrderConfirmation } from "./order-confirmation.svg?react";
export { default as IconTwitter } from "./twitter.svg?react";
