
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ImageType = {
  PRODUCT: 'PRODUCT',
  CATEGORY_PREVIEW: 'CATEGORY_PREVIEW',
  GALLERY_1: 'GALLERY_1',
  GALLERY_2: 'GALLERY_2',
  GALLERY_3: 'GALLERY_3'
} as const

export type ImageType = (typeof ImageType)[keyof typeof ImageType]


export const PaymentMethod = {
  E_MONEY: 'E_MONEY',
  CASH: 'CASH'
} as const

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod]
