import { BaseLayout, TailwindIndicator } from '@/components';
import { Providers } from '@/context';
import { cn } from '@/helpers';
import type { Metadata } from 'next';
import { FontSans } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={cn('', FontSans.className)}>
      <body
        className={cn('relative selection:bg-brand-300 selection:text-white')}
      >
        <Providers>
          <BaseLayout>{children}</BaseLayout>
          <TailwindIndicator />
        </Providers>
      </body>
    </html>
  );
}
